### ISSUE TITLE
Can't apply anything

### ISSUE THREAD

**Issue by Alexhhhc** [realmazharhussain/gdm-settings#1]
On both latest git version(0.2+alpha+0+g5a0cc83-1) and stable version(0.2+alpha-1),anything can't be applied(no matter run byt normal user or root),and the command line shows this:

```
(gdm-settings:20369): Gtk-WARNING **: 21:34:17.511: Unknown key gtk-button-images in /home/Alexhhh/.config/gtk-4.0/settings.ini

(gdm-settings:20369): Gtk-WARNING **: 21:34:17.511: Unknown key gtk-menu-images in /home/Alexhhh/.config/gtk-4.0/settings.ini

(gdm-settings:20369): Gtk-WARNING **: 21:34:17.511: Unknown key gtk-toolbar-style in /home/Alexhhh/.config/gtk-4.0/settings.ini
Traceback (most recent call last):
  File "/usr/bin/gdm-settings", line 360, in <lambda>
    widgets.apply_button.connect("clicked", lambda x: on_apply())
  File "/usr/bin/gdm-settings", line 324, in on_apply
    set_theme_settings()
  File "/usr/bin/gdm-settings", line 311, in set_theme_settings
    theme_settings.background_image = widgets.bg_image_chooser.get_file().get_path()
AttributeError: 'NoneType' object has no attribute 'get_path'
```

Arch Linux,gnome 41.3

**Comment by realmazharhussain** [comment]
Thanks for reporting the issue.

It seems to be an issue in the app itself but it is working fine for me. So, it may be an issue with the AUR packages.

Try running this [AppImage](https://github.com/realmazharhussain/gdm-settings/releases/download/v0.2-alpha/Login_Manager_Settings-nodeps.AppImage) version of the app and let me know if it works.

**Note:** The AppImage does not include dependencies. So, it is better to keep the AUR packages for dependencies.

**Comment by realmazharhussain** [comment]
Thank you for reporting the issue. I have fixed it. Update `gdm-settings-git` package and check if it works for you.

Don't forget to inform me.

**Comment by Alexhhhc** [comment]
It works!Thank you for developing such a useful tool!

**Comment by realmazharhussain** [comment]
You are welcome!
