### ISSUE TITLE
GDM power plugin controls

### ISSUE THREAD

**Issue by carneeki** [realmazharhussain/gdm-settings#103]
### Description

Being able to change settings for power would save a lot of people headaches when trying to control autosuspend (and other similar power related settings) for login.

### Explaination

Here are the `gsettings` of greatest interest:

* `org.gnome.settings-daemon.plugins.power ambient-enabled`
* `org.gnome.settings-daemon.plugins.power idle-brightness`
* `org.gnome.settings-daemon.plugins.power idle-dim`
* `org.gnome.settings-daemon.plugins.power power-button-action`
* `org.gnome.settings-daemon.plugins.power power-saver-profile-on-low-battery`
* `org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout`
* `org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type`
* `org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout`
* `org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type`

Thanks!

**Comment by realmazharhussain** [comment]
Version 1.0 is in beta now. So, this feature will have to wait for the next version.

**Comment by realmazharhussain** [comment]
UI for this feature is complete.

<picture>
  <source srcset="https://user-images.githubusercontent.com/67191572/192590798-c1905ac6-46c9-418d-8f84-bb421f59b7f6.png" media="(prefers-color-scheme: dark)">
  <img src="https://user-images.githubusercontent.com/67191572/192591127-61879481-7990-4fb5-9b0c-8d80aa7cf91f.png">
</picture>

Now, I just need to implement actual settings for it.

**Comment by carneeki** [comment]
This looks great!

**Comment by realmazharhussain** [comment]
Done.

Relevant commit: b34452823947b75490d21c55e65861c300e2f253.
