### ISSUE TITLE
Applying settings works only once

### ISSUE THREAD

**Issue by ItsJamie9494** [realmazharhussain/gdm-settings#104]
### What happened?

When enabling a logo to show on GDM, it becomes impossible to disable. Attempting to disable it returns a traceback error:

```python
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 130, in <lambda>
    self._finish_callback = lambda self, task, nothing: finish_callback()
  File "/app/lib/python3.9/site-packages/gdm_settings/window.py", line 121, in on_apply_finished
    if self.apply_task.finish():
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 160, in finish
    raise value
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 145, in _thread_cb
    retval = self._function()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 398, in apply_settings
    self.apply_shell_theme_settings()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 238, in apply_shell_theme_settings
    compiled_file = gr_utils.compile(shelldir,
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 98, in compile
    extract_default_theme(temp_theme_dir)
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 64, in extract_default_theme
    resource_list = getstdout(["gresource", "list", env.HOST_ROOT + gresource_file]).decode().splitlines()
TypeError: can only concatenate str (not "NoneType") to str
```

### Expected behavior

The logo would be removed

### To Reproduce

1. Enable a Logo
2. Attempt to disable it by toggling the checkbox

### Application Version

gdm-settings v1.0-beta.4

### Source

Flatpak

### Environment

- **OS**:  Fedora 37
- **GNOME**: 43

**Comment by realmazharhussain** [comment]
There is an issue but from the error output, it seems like it is not an issue with the logo toggle.

Run the app with `-v` option and provide its output here.

**Comment by ItsJamie9494** [comment]
Full output:
```
jamie in ~ took 2m56s 
❯ flatpak run io.github.realmazharhussain.GdmSettings -v
INFO: Application Version    = 1.0-beta.4
INFO: Operating System       = Fedora Linux 37 (Workstation Edition Prerelease)
INFO: PackageType            = Flatpak
INFO: TEMP_DIR               = /run/user/1000/app/io.github.realmazharhussain.GdmSettings
INFO: HOST_DATA_DIRS         = /usr/local/share:/usr/share
INFO: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO: UbuntuGdmGresourceFile = None
INFO: pkexec version 121
INFO: GLib 2.72.3
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 130, in <lambda>
    self._finish_callback = lambda self, task, nothing: finish_callback()
  File "/app/lib/python3.9/site-packages/gdm_settings/window.py", line 121, in on_apply_finished
    if self.apply_task.finish():
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 160, in finish
    raise value
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 145, in _thread_cb
    retval = self._function()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 398, in apply_settings
    self.apply_shell_theme_settings()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 238, in apply_shell_theme_settings
    compiled_file = gr_utils.compile(shelldir,
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 98, in compile
    extract_default_theme(temp_theme_dir)
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 64, in extract_default_theme
    resource_list = getstdout(["gresource", "list", env.HOST_ROOT + gresource_file]).decode().splitlines()

```

**Comment by realmazharhussain** [comment]
I could not reproduce the issue on my laptop. Could you send me a screen recording?

**Comment by ItsJamie9494** [comment]
Strange, it was fixed when I attempted to record. Closing for now :)

**Comment by LaBatata101** [comment]
I'm getting the same error with any setting I try to change.

### Application Version
gdm-settings v2.alpha
### Source
AUR (gdm-settings-git)
### Environment
- **OS**: Manjaro Linux
- **GNOME**: 42.4

**Comment by realmazharhussain** [comment]
@LaBatata101, would you like to share a screen recording of the issue?

**Comment by realmazharhussain** [comment]
What is the output of the following command on your system?

```bash
ls -1 /usr/share/gnome-shell/gnome-shell-theme.gresource*
```

**Comment by federicomrc** [comment]
I get `/usr/share/gnome-shell/gnome-shell-theme.gresource` (Fedora 36 workstation, GNOME 42.4, app version 1.0)

**Comment by LaBatata101** [comment]
> @LaBatata101, would you like to share a screen recording of the issue?

@realmazharhussain  here it is.

https://user-images.githubusercontent.com/20308796/192116671-f1add3ed-2000-4322-9393-7904e0c2e788.mp4



> What is the output of the following command on your system?
`ls -1 /usr/share/gnome-shell/gnome-shell-theme.gresource*`

```bash
$ ls -1 /usr/share/gnome-shell/gnome-shell-theme.gresource*
/usr/share/gnome-shell/gnome-shell-theme.gresource
```

**Comment by AkselMeola** [comment]
Same issue here.
gdm-settings v1.0 using flatpak

Happens after I wan to change background image back to none. 
Odd is that on the very first apply it asked for a root password, but on the next tries it just fails with no password prompt.


```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 130, in <lambda>
    self._finish_callback = lambda self, task, nothing: finish_callback()
  File "/app/lib/python3.9/site-packages/gdm_settings/window.py", line 121, in on_apply_finished
    if self.apply_task.finish():
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 160, in finish
    raise value
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 145, in _thread_cb
    retval = self._function()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 398, in apply_settings
    self.apply_shell_theme_settings()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 238, in apply_shell_theme_settings
    compiled_file = gr_utils.compile(shelldir,
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 98, in compile
    extract_default_theme(temp_theme_dir)
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 64, in extract_default_theme
    resource_list = getstdout(["gresource", "list", env.HOST_ROOT + gresource_file]).decode().splitlines()
TypeError: can only concatenate str (not "NoneType") to str
```

On a side note: Anyway to get rid of all these settings and revert to default?

**Comment by LaBatata101** [comment]
> Happens after I wan to change background image back to none. Odd is that on the very first apply it asked for a root password, but on the next tries it just fails with no password prompt.

Forgot to mention, this happened to me as well.

**Comment by AkselMeola** [comment]
Thought that it might cache the privilege escalation, but after reboot no change.

**Comment by AkselMeola** [comment]
But good news is that either uninstalling(i reinstalled to test) or removing the `.var/app/io.github.realmazharhussain.GdmSettings` restored the old state. (didn't catch which one helped)

Reinstall did not help and removing that folder also did not restore the app into working condition tho.

**Comment by realmazharhussain** [comment]
Before applying settings, the app is supposed to backup the file `/usr/share/gnome-shell/gnome-shell-theme.gresource` as `/usr/share/gnome-shell/gnome-shell-theme.gresource.default`. It seems like it is not doing that for some reason.

**Comment by realmazharhussain** [comment]
@AkselMeola

> Anyway to get rid of all these settings and revert to default?

1. Reinstall gnome-shell package (or gnome-shell-common package if that exists in your distro).
2. Remove the file `/etc/dconf/db/gdm.d/95-gdm-settings`.
3. Run the command `dconf update` as root (or with sudo).

**Comment by realmazharhussain** [comment]
Is everyone having this issue also using Gradience?

**Comment by xaaavier** [comment]
Same problem here, but without using Gradience..
OS : Debian Sid
`Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/gdm_settings/utils.py", line 130, in <lambda>
    self._finish_callback = lambda self, task, nothing: finish_callback()
  File "/usr/local/lib/python3/dist-packages/gdm_settings/window.py", line 121, in on_apply_finished
    if self.apply_task.finish():
  File "/usr/local/lib/python3/dist-packages/gdm_settings/utils.py", line 160, in finish
    raise value
  File "/usr/local/lib/python3/dist-packages/gdm_settings/utils.py", line 145, in _thread_cb
    retval = self._function()
  File "/usr/local/lib/python3/dist-packages/gdm_settings/settings.py", line 398, in apply_settings
    self.apply_shell_theme_settings()
  File "/usr/local/lib/python3/dist-packages/gdm_settings/settings.py", line 238, in apply_shell_theme_settings
    compiled_file = gr_utils.compile(shelldir,
  File "/usr/local/lib/python3/dist-packages/gdm_settings/gr_utils.py", line 98, in compile
    extract_default_theme(temp_theme_dir)
  File "/usr/local/lib/python3/dist-packages/gdm_settings/gr_utils.py", line 64, in extract_default_theme
    resource_list = getstdout(["gresource", "list", env.HOST_ROOT + gresource_file]).decode().splitlines()
TypeError: can only concatenate str (not "NoneType") to str
`

**Comment by LaBatata101** [comment]
> Is everyone having this issue also using Gradience?

Nope. I had used it before, but I uninstalled it before installing gdm-settings.

**Comment by realmazharhussain** [comment]
1. Reinstall `gnome-shell` package (or `gnome-shell-common` package if it exists in your distro's repos)
1. Run this app in the terminal
1. Apply your settings
1. Provide itsoutput here

**Comment by LaBatata101** [comment]
> 1. Reinstall `gnome-shell` package (or `gnome-shell-common` package if it exists in your distro's repos)
> 
>     2. Run this app in the terminal
> 
>     3. Apply your settings
> 
>     4. Provide its output here

It worked after reinstalling `gnome-shell`, I changed the settings multiple times and got no errors.

**Comment by pawelswiszcz** [comment]
I think I have the same issue. 
When I applied changes the first time [it was a background image] after the password prompt the gnome-shell crashed. Restart the system- new wallpaper was set [but in very low resolution]. Setting second-time background gives the error below.
Reinstalling the package gnome-shell not worked. 

Login manager flatpack version. 
System:
GNOME 42.4,
Manjaro 

```

(gdm-settings:2): Gtk-WARNING **: 14:26:17.195: GtkImage 0x55dd4be50790 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(gdm-settings:2): Gtk-WARNING **: 14:26:17.195: GtkImage 0x55dd4be50920 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(gdm-settings:2): Gtk-WARNING **: 14:26:17.196: GtkImage 0x55dd4be91160 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(gdm-settings:2): Gtk-WARNING **: 14:26:17.196: GtkImage 0x55dd4be912f0 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(gdm-settings:2): Gtk-WARNING **: 14:27:43.828: Couldn't unexport handle for GdkX11Toplevel surface, unsupported windowing system
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 130, in <lambda>
    self._finish_callback = lambda self, task, nothing: finish_callback()
  File "/app/lib/python3.9/site-packages/gdm_settings/window.py", line 121, in on_apply_finished
    if self.apply_task.finish():
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 160, in finish
    raise value
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 145, in _thread_cb
    retval = self._function()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 398, in apply_settings
    self.apply_shell_theme_settings()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 238, in apply_shell_theme_settings
    compiled_file = gr_utils.compile(shelldir,
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 98, in compile
    extract_default_theme(temp_theme_dir)
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 64, in extract_default_theme
    resource_list = getstdout(["gresource", "list", env.HOST_ROOT + gresource_file]).decode().splitlines()
TypeError: can only concatenate str (not "NoneType") to str

```

**Comment by xaaavier** [comment]
> I think I have the same issue. When I applied changes the first time [it was a background image] after the password prompt the gnome-shell crashed. Restart the system- new wallpaper was set [but in very low resolution]. The setting second-time background gives the error below. Reinstalling the package gnome-shell not worked.
> 
> Login manager flatpack version. System: GNOME 42.4, Manjaro
> 
> ```
> 
> (gdm-settings:2): Gtk-WARNING **: 14:26:17.195: GtkImage 0x55dd4be50790 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.
> 
> (gdm-settings:2): Gtk-WARNING **: 14:26:17.195: GtkImage 0x55dd4be50920 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.
> 
> (gdm-settings:2): Gtk-WARNING **: 14:26:17.196: GtkImage 0x55dd4be91160 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.
> 
> (gdm-settings:2): Gtk-WARNING **: 14:26:17.196: GtkImage 0x55dd4be912f0 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.
> 
> (gdm-settings:2): Gtk-WARNING **: 14:27:43.828: Couldn't unexport handle for GdkX11Toplevel surface, unsupported windowing system
> Traceback (most recent call last):
>   File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 130, in <lambda>
>     self._finish_callback = lambda self, task, nothing: finish_callback()
>   File "/app/lib/python3.9/site-packages/gdm_settings/window.py", line 121, in on_apply_finished
>     if self.apply_task.finish():
>   File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 160, in finish
>     raise value
>   File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 145, in _thread_cb
>     retval = self._function()
>   File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 398, in apply_settings
>     self.apply_shell_theme_settings()
>   File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 238, in apply_shell_theme_settings
>     compiled_file = gr_utils.compile(shelldir,
>   File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 98, in compile
>     extract_default_theme(temp_theme_dir)
>   File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 64, in extract_default_theme
>     resource_list = getstdout(["gresource", "list", env.HOST_ROOT + gresource_file]).decode().splitlines()
> TypeError: can only concatenate str (not "NoneType") to str
> ```

install Gnome 43 solve this issue for me.

**Comment by realmazharhussain** [comment]
@pawelswiszcz, After reinstalling `gnome-shell`, does the app work one more time before starting to have this issue again, or does it just not work even once?

**Comment by pawelswiszcz** [comment]
> @pawelswiszcz, After reinstalling `gnome-shell`, does the app work one more time before starting to have this issue again, or does it just not work even once?

After reinstalling `gnome-shell` when I click `Apply` the password prompt is showing. When the password is correct the whole gnome-shell is freezing. Can't do anything only kill gnome or restart the PC. The new wallpaper is set I gdm but in low resolution

**Comment by realmazharhussain** [comment]
Here is a flatpak [gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/9689944/gdm-settings.flatpak.zip).

1. Reinstall GNOME Shell
2. Unzip and Install the flatpak
3. Open the app
4. Apply settings twice
5. Report if it works

**Comment by realmazharhussain** [comment]
> the whole gnome-shell is freezing. Can't do anything only kill gnome or restart the PC. The new wallpaper is set I gdm but in low resolution

You might want to create new issues for those problems after this one is fixed.

**Comment by pawelswiszcz** [comment]
> Here is a flatpak [gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/9689944/gdm-settings.flatpak.zip).
> 
>     1. Reinstall GNOME Shell
> 
>     2. Unzip and Install the flatpak
> 
>     3. Open the app
> 
>     4. Apply settings twice
> 
>     5. Report if it works

The same:
Errors:
```
(gdm-settings:2): Gtk-WARNING **: 11:05:49.339: GtkImage 0x55efc8261920 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(gdm-settings:2): Gtk-WARNING **: 11:05:49.339: GtkImage 0x55efc82aa2e0 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(gdm-settings:2): Gtk-WARNING **: 11:05:49.339: GtkImage 0x55efc82aa470 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(gdm-settings:2): Gtk-WARNING **: 11:05:58.628: Couldn't unexport handle for GdkX11Toplevel surface, unsupported windowing system

(gdm-settings:2): Gdk-CRITICAL **: 11:06:28.088: gdk_device_get_n_axes: assertion 'GDK_IS_DEVICE (device)' failed
```

**Comment by realmazharhussain** [comment]
@pawelswiszcz

Does the password prompt show up for the 2nd time after you reboot, without you having to reinstall GNOME Shell?

**Comment by pawelswiszcz** [comment]
> @pawelswiszcz
> 
> Does the password prompt show up for the 2nd time after you reboot, without you having to reinstall GNOME Shell?

No. It's not showing.

**Comment by realmazharhussain** [comment]
@pawelswiszcz,

- You followed all the steps mentioned in [this comment](https://github.com/realmazharhussain/gdm-settings/issues/104#issuecomment-1264295196) including reinstalling GNOME Shell
- Applied the settings from the app
- Password prompt showed up
- Force rebooted the computer
- Applied the settings again
- Password prompt did not show up

Is that correct?

**Comment by ThatOneCalculator** [comment]
This happens to me too :(

**Comment by realmazharhussain** [comment]
Please! Reinstall package `gnome-shell` (or `gnome-shell-common` if it exists) and upgrade this app to the latest stable version (currently v1.1).

**Comment by ThatOneCalculator** [comment]
They're already the latest version, I reinstalled and it still happens!!!

**Comment by realmazharhussain** [comment]
So,

1. You reinstalled `gnome-shell-common` (or `gnome-shell`) package
2. Updated 'Login Manager Settings' app to v1.1
3. You still cannot apply settings 2 times in a row

Is that correct?

**Comment by ThatOneCalculator** [comment]
I'll try again and verify its the latest version tomorrow
