### ISSUE TITLE
An Option to Backup/Export current applied settings when using Flatpak 

### ISSUE THREAD

**Issue by Raul1198** [realmazharhussain/gdm-settings#108]
### Description

An Export/Backup option in the Flatpak version 

### Explaination

It would be easier to have a backup file of the applied settings in case the default one is not to your liking or you want to have the same settings in another system or you're clean/reinstalling a distributions and want your old gdm settings you applied previously

**Comment by realmazharhussain** [comment]
Seems like a good feature to have.

Right now, even though this option is not available in application's interface, you can still import/export currently applied settings for the flatpak version since all the settings are stored in a single file `$HOME/.var/app/io.github.realmazharhussain.GdmSettings/config/glib-2.0/keyfile`

**Comment by Raul1198** [comment]
thanks for the reply, so if i copy the keyfile and paste in a newly installed flatpak will it detect the settings. Or use it as import setting while using the appimage and other format.

**Comment by realmazharhussain** [comment]
Unfortunately, it only works with the flatpak.

**Comment by realmazharhussain** [comment]
> so if i copy the keyfile and paste in a newly installed gdm flatpak location(.var/app/io.github.realmazharhussain.GdmSettings/config/glib-2.0/settings/) will it detect the settings.

Yes

**Comment by Raul1198** [comment]
Got it

**Comment by realmazharhussain** [comment]
![Screenshot from 2022-10-10 08-21-30](https://user-images.githubusercontent.com/67191572/194800760-b224a490-bc3e-4e4f-b4df-3820814854a5.png)
