### ISSUE TITLE
Use the same mouse settings from System 

### ISSUE THREAD

**Issue by Raul1198** [realmazharhussain/gdm-settings#109]
### Description

Same mouse settings applied to gdm from system settings 

### Explaination

The mouse sensitivity and acceleration same as its in the system because since there no numerical value in gnome for mouse sensitivity it hard to maintain the same consistency pointer speed in the system and in the lockscreen and gdm. So if gdm could show an option to import from system it would be same for system, lockscreen and login screen

**Comment by realmazharhussain** [comment]
This feature is disabled in Flatpak version of the app due to technical reasons but it is available in AppImage and other packaging formats.

**Comment by Raul1198** [comment]
thanks
