### ISSUE TITLE
Setup default monitor settings

### ISSUE THREAD

**Issue by alessiocelentano** [realmazharhussain/gdm-settings#11]
It would be great if it were possible to change monitor settings. Copying the current DE settings is fine most of the time, so it would be enough to add a button which executes these two lines:
```
cp ~/.config/monitors.xml /var/lib/gdm/.config/
chown gdm:gdm /var/lib/gdm/.config/monitors.xml
```

**Comment by realmazharhussain** [comment]
Thank you for opening this issue. I will start working on it as soon as possible.

**Comment by acerspyro** [comment]
While you're at it, it would be really nice to just have a button to "Apply current display settings to login screen".

**Comment by realmazharhussain** [comment]
Done. The feature has been added to the app. There is a new 'Tools' page which contains a button to apply current display/monitor settings to GDM.

Test it out and let me know if it works for you.

**Comment by alessiocelentano** [comment]
It works. Thanks
