### ISSUE TITLE
Cannot reset default login background

### ISSUE THREAD

**Issue by federicomrc** [realmazharhussain/gdm-settings#110]
### What happened?

After changing the login background it is not possible to change it again or to revert it to the original one (the default dark-gray).

### Expected behavior

It should be possible to change login background multiple times and reverting it to the original gnome default

### To Reproduce

Set the login background image to a custom image using the file selector and apply this change. 
Log out as requested. Log in again.

At this point the background cannot be changed again (either changing it to another image, nor reverting it to the original value, i.e. the dark gray solid color).

Using the option "Reset settings" in the main menu doesn't work as well.

### Detailed Explaination (Optional)

Running the app with: `flatpak run io.github.realmazharhussain.GdmSettings -v` shows the following log when pressing "Apply" 

```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 130, in <lambda>
    self._finish_callback = lambda self, task, nothing: finish_callback()
  File "/app/lib/python3.9/site-packages/gdm_settings/window.py", line 121, in on_apply_finished
    if self.apply_task.finish():
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 160, in finish
    raise value
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 145, in _thread_cb
    retval = self._function()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 398, in apply_settings
    self.apply_shell_theme_settings()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 238, in apply_shell_theme_settings
    compiled_file = gr_utils.compile(shelldir,
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 98, in compile
    extract_default_theme(temp_theme_dir)
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 64, in extract_default_theme
    resource_list = getstdout(["gresource", "list", env.HOST_ROOT + gresource_file]).decode().splitlines()
TypeError: can only concatenate str (not "NoneType") to str

```

### Application Version

1.0

### Source

Flatpak

### Environment

- **OS**: Fedora 36 workstation
- **GNOME**: 42.4
- **Display server**: Wayland

**Comment by federicomrc** [comment]
Some additional info:

```
INFO: Application Version    = 1.0
INFO: Operating System       = Fedora Linux 36 (Workstation Edition)
INFO: PackageType            = Flatpak
INFO: TEMP_DIR               = /run/user/1000/app/io.github.realmazharhussain.GdmSettings
INFO: HOST_DATA_DIRS         = /usr/local/share:/usr/share
INFO: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO: UbuntuGdmGresourceFile = None
INFO: pkexec version 0.120
INFO: GLib 2.72.3
```

**Comment by realmazharhussain** [comment]
What is the output of the following command on your system?

```bash
ls -1 /usr/share/gnome-shell/gnome-shell-theme.gresource*
```

**Comment by realmazharhussain** [comment]
This issue seems to be exactly the same as #104. So, we should continue this conversation there. Closing this one for now.
