### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by edoardge** [realmazharhussain/gdm-settings#120]
### What happened?

Worked once and not anymore

### Expected behavior

Update fail

### To Reproduce

When I updated to 1.0 version I tried to set up to add new cursor theme and when I applied settings it didn't do anything and the settings didn't applied...

### Application Version

1.0

### Source

flatpak

### Environment

- **OS**: Fedora 37
- **GNOME**: 43

**Comment by edoardge** [comment]
I was reading the issues and followed your suggestions and it worked...
I reinstalled the gnome-shell package and set up settings again and they applied...
Thank you...

**Comment by realmazharhussain** [comment]
Can you apply them again?

**Comment by realmazharhussain** [comment]
Closing as not planned since this issue is a duplicate of #104.
