### ISSUE TITLE
Icons and menus are duplicated Fedora 36

### ISSUE THREAD

**Issue by j1cs** [realmazharhussain/gdm-settings#121]
### What happened?

After applying changes gdm looks funny when you click in the menus and icons are like duplicate (upper right corner):
![](https://rimgo.bcow.xyz/uhjoEI4.jpg)
![](https://rimgo.bcow.xyz/d4SdFVZ.jpg)
![](https://rimgo.totaldarkness.net/uaLwcTU.jpg)

### Expected behavior

Should look normal

### To Reproduce

After installing apply [Flat-Remix-Blue-Darkest-fullPanel ](https://github.com/daniruiz/flat-remix)in the Shell option.

### Detailed Explaination (Optional)

The first time gdm opens in the upper right corner you can see the icons are duplicate. looks like are overlapping each other.
When you open the menus they open without problem, but when they are closed the menu is blurred and stuck.
And when you click to type the password the input and the image overlaps the previous state.

### Application Version

v1.0

### Source

Flatpak

### Environment

- **OS**: Fedora 36
- **GNOME**:  42.5

**Comment by realmazharhussain** [comment]
Here is a flatpak [gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/9689944/gdm-settings.flatpak.zip).

1. Reinstall GNOME Shell
2. Unzip and Install the flatpak
3. Open the app
4. Apply settings
5. Tell me if it solves your problem

**Comment by realmazharhussain** [comment]
OK. I tried [Flat-Remix-Blue-Darkest-fullPanel](https://github.com/daniruiz/flat-remix-gnome) and it seems like that theme does not support GDM. You can open this issue on their repo.

In the meantime, if you would like to use that theme without this problem, you could just choose a background. Both color and image backgrounds resolve this issue.

**Comment by j1cs** [comment]
I understand what did you say. But when you install `flat-remix-gnome` automatically change the gdm theme with "Flat-Remix-Blue-Light" https://github.com/daniruiz/flat-remix-gnome/blob/master/Makefile#L6 and the bug doesn't happens. 
why does this behavior occur?

**Comment by realmazharhussain** [comment]
I'll look into it.

**Comment by realmazharhussain** [comment]
So, I installed flat-remix-gnome, without using this app, from source and also from chaotic-aur. It seems to have this problem regardless.

**Comment by j1cs** [comment]
> So,
> 
> I installed flat-remix-gnome, without using this app, from source and also from chaotic-aur. It seems to have this problem regardless.

if you please can you provide me with evidence for this? with this i can report the issue with this two previous ways for installing
