### ISSUE TITLE
Doesn't work on Debian-like systems

### ISSUE THREAD

**Issue by wjt** [realmazharhussain/gdm-settings#125]
### What happened?

An error toast popped up at the bottom of the window, then disappeared too fast to read or take a screenshot.

### Expected behavior

Monitor settings etc. applied to login screen

### To Reproduce

1. Use a Debian-based system
1. Open the app
2. Select *Display*
3. Next to *Apply current display settings*, pick *Apply*

Probably every other action would have the same result.

### Detailed Explaination (Optional)

I caught the contents of the script that gets pkexec'd as follows:

```
#!/bin/sh
machinectl shell {gr_utils.GdmUsername}@ /usr/bin/env gsettings set experimental-features "['scale-monitor-framebuffer']" &>/dev/null
install -Dm644 /sysroot/home/wjt/.var/app/io.github.realmazharhussain.GdmSettings/config/monitors.xml ~gdm/.config/monitors.xml
chown gdm: ~gdm/.config/monitors.xml
```

Something has failed to substitute GdmUsername here I think.

And its mode:

```
--wxrw--wt 1 wjt wjt 309 Oct 21 09:34 /run/user/1001/app/io.github.realmazharhussain.GdmSettings/run-elevated
```

Unconventional choice to make the file world-writable but only readable by the group. Is this intentional? Surely not.

Anyway. In the journal we see:

```
Oct 21 09:32:52 camille org.gnome.Software.desktop[4558]: /run/user/1001/app/io.github.realmazharhussain.GdmSettings/run-elevated: 2: machinectl: not found
```

No `machinectl` on Endless OS! But as above I think this would have failed anyway because of the unsubstituted `{gr_utils.GdmUsername}@`.

```
Oct 21 09:32:52 camille org.gnome.Software.desktop[4560]: chown: spécification incorrecte: « gdm: »
```

On Debian-like systems, GDM runs as user & group `Debian-gdm`, for better or for worse.

### Application Version

gdm-settings v1.1

### Source

Flathub

### Environment

- **OS**: Endless OS development branch
- **GNOME**: 41.3

**Comment by wjt** [comment]
https://github.com/realmazharhussain/gdm-settings/blob/44aad94d8c555023908754e73df538e6250628d7/src/utils.py#L101

In the small, you want `0o755` in octal, which is `493` in decimal. Right now you are setting mode `755` in decimal, which is `0o1363` in octal. But more generally I think you can assume that the user's temporary directory is not accessible to other users. Rather than manually creating and deleting the directory, you should use `tempfile.TemporaryDirectory` or preferably `tempfile.NamedTemporaryFile` (passing a symbolic 'mode') to create the file with the correct mode in one step, and then erase it when the `with` block ends.

**Comment by realmazharhussain** [comment]
Could you provide values of `OS_ID` and `OS_ID_LIKE` as found in `/etc/os-release` file on your system?

**Comment by wjt** [comment]
```
NAME="Endless OS"
VERSION="5.0.0"
ID="endless"
ID_LIKE="ubuntu debian"
PRETTY_NAME="Endless OS 5.0.0"
VERSION_ID="5.0.0"
HOME_URL="https://endlessos.com/"
LOGO=endlessos
BUILD_ID="221020-230009"
```

**Comment by realmazharhussain** [comment]
This issue should be fixed in the latest source code. I will soon upload a flatpak for you to actually test it.

**Comment by realmazharhussain** [comment]
[gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/9843802/gdm-settings.flatpak.zip)
