### ISSUE TITLE
Incorrect Flatpak package name for installation

### ISSUE THREAD

**Issue by kianmeng** [realmazharhussain/gdm-settings#127]
### What happened?

In step 3 within https://github.com/realmazharhussain/gdm-settings/wiki/Install#flatpak:

```diff
- flatpak install io.github.realmazharhusain.GdmSettings
+ flatpak install io.github.realmazharhussain.GdmSettings
```

### Expected behavior

See above.

### To Reproduce

See above.

### Application Version

None

### Source

Flatpak

### Environment

- **OS**: Ubuntu 22.10
- **GNOME**: 43

**Comment by realmazharhussain** [comment]
Fixed.
