### ISSUE TITLE
List user installed themes for Shell and Icons

### ISSUE THREAD

**Issue by LaBatata101** [realmazharhussain/gdm-settings#128]
### Description

Currently, `gdm-settings` only show the themes installed system-wide (I'm not sure about this), and I have a custom Shell and Icons theme installed under `.themes` and `.icons` in my home directory that I want to use, so it would be pretty cool if `gdm-settings` could use custom themes.

**Comment by realmazharhussain** [comment]
GDM does not have access to files (including themes) in your home directory
