### ISSUE TITLE
Add support for fractional scaling

### ISSUE THREAD

**Issue by mimi89999** [realmazharhussain/gdm-settings#13]
Hello,
I'm using fractional scaling with a scale factor of 125% in the shell. However, I don't see any way to set that in GDM3. Would it be possible to do that?

**Comment by realmazharhussain** [comment]
You can already set font size and font scaling. As far as real fractional scaling is concerned, I do not think gnome-shell supports it in a wayland session. Since GDM runs inside a minimal gnome/wayland session, I think it would not be possible for GDM.

That is what I think. I may be wrong. I do not know any of this for sure.

**Comment by mimi89999** [comment]
It is supported on wayland. You just need to `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
`. https://wiki.archlinux.org/title/HiDPI#Wayland

**Comment by realmazharhussain** [comment]
>  You just need to `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`

OK, I tried `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`. It works fine inside a user session. But GDM does not respect this setting. Maybe because it is a feature of Mutter and Mutter is not running during the login process.

**Comment by Tschrock** [comment]
In order for that command to work, I had to run it as the gdm user as mentioned here <https://bbs.archlinux.org/viewtopic.php?id=261081>

```sh
cyber@Cyber-LT:~$ machinectl shell gdm@ /bin/bash
gdm@Cyber-LT:~$ gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
```

I can confirm this works on at least Ubuntu 21.10 and 22.04

**Comment by MatthewScholefield** [comment]
Note, I had the same issue and couldn't get fractional scaling to be enabled when rendering GDM with Wayland, but I was able to get it to work with GDM configured to use Xorg. I did this with the following changes:

 1. Change GDM to use Xorg by editing `/etc/gdm3/custom.conf` to set `PreferredDisplayServer=xorg` under `[daemon]`
 2. Enable fractional scaling within Xorg for the gdm user with `machinectl shell gdm@ /bin/bash` followed by `gsettings set org.gnome.mutter experimental-features "['x11-randr-fractional-scaling']"`
 3. Login to a GNOME Xorg session and enable fractional scaling. Then copy these display settings to gdm with this tool
 4. Restart

After this the login manager should be fractionally scaled rendering with Xorg but still allow starting your session with Wayland.

**Comment by realmazharhussain** [comment]
Hi, some support for fractional scaling has been added.

The 'Apply Current Display Settings' also applies fractional scaling now. But it only works for Wayland users i.e. users whose `monitors.xml` was generated inside a Wayland session.
