### ISSUE TITLE
Enable Logo not working for Archlinux

### ISSUE THREAD

**Issue by m20191201** [realmazharhussain/gdm-settings#132]
### What happened?

I am having an issue with the "Enable Logo" setting inside of the Miscellaneous tab. I have enabled the setting and put a ".png" image of Archlinux's logo but it is not showing up on the login screen.

### Expected behavior

I would expect the logo to be added below the user list

### To Reproduce

Turn on "Enable Logo" and select a file in /usr/share/archlinux/logos/g2424.png

### Application Version

1.1

### Source

Flatpak, AUR

### Environment

- **OS**: Archlinux
- **GNOME**: 43

**Comment by realmazharhussain** [comment]
Does the file `/etc/gdm-logo` exist? Is it the same as the file you chose as the logo?

**Comment by m20191201** [comment]
yes, same image as I choose

**Comment by realmazharhussain** [comment]
Does the file `/etc/dconf/db/gdm.d/95-gdm-settings` contain the line `logo='/etc/gdm-logo'`?

Can be found by running the following command in the terminal.

```bash
grep logo /etc/dconf/db/gdm.d/95-gdm-settings
```

**Comment by m20191201** [comment]
~ >>> grep logo /etc/dconf/db/gdm.d/95-gdm-settings                                                                              
logo='/etc/gdm-logo'
~ >>>

**Comment by realmazharhussain** [comment]
I do not understand what 100600 means. What is the output of `ls -l /etc/gdm-logo`?

**Comment by m20191201** [comment]
~ >>> ls -l /etc/gdm-logo                                                                                                        
-rw------- 1 root root 43550 Nov  6 21:50 /etc/gdm-logo

**Comment by realmazharhussain** [comment]
Run the following command and see if it solves your problem.

```bash
sudo chmod 644 /etc/gdm-logo
```

**Comment by m20191201** [comment]
ok, fixed the problem, thank you so much!

**Comment by realmazharhussain** [comment]
You are welcome.

But the problem has not been fixed completely. You will face the same issue the next time you apply settings. So, the GitHub issue should not have been closed.

I already have a fix. I'll push it to GitHub when I open my laptop and this GitHub issue will automatically be closed. Then, you'll be able to use `gdm-settings-git` AUR package which will have the problem properly resolved.

**Comment by realmazharhussain** [comment]
Now, the problem has been fixed properly.
