### ISSUE TITLE
Apply current display settings does not work when using Flatpak

### ISSUE THREAD

**Issue by remidebette** [realmazharhussain/gdm-settings#133]
### What happened?

Thanks for the nice app.

In Display > "Apply current display settings" does not work on a fresh Ubuntu 22 install

### Expected behavior

Clicking on this button is expected to make the login screen resolution immediately as the main settings

### To Reproduce

Test on an environment without the following: `~/.config/monitors.xml` and the folder `/var/lib/gdm3/.config`
(like a fresh install)

### Detailed Explanation (Optional)

I understand this button is simply doing this command:
```bash
sudo cp ~/.config/monitors.xml /var/lib/gdm3/.config/monitors.xml
```

As I posted in this link: https://askubuntu.com/a/1438526/644051
To me this issue is 2-fold,
* `~/.config/monitors.xml` is not automatically created by Ubuntu, if absent an error message should prompt the user to initialize it via the main Settings > Display (any change should create it)

* Even after doing the above, the Apply button did not work until I created the `/var/lib/gdm3/.config` folder manually.
The tool should create it automatically if not there

### Application Version

latest

### Source

Flatpak

### Environment

- **OS**: Ubuntu 22.04
- **GNOME**: 41.3

**Comment by mystrdat** [comment]
Doesn't seem to work on Silverblue either

**Comment by realmazharhussain** [comment]
What is the output shown in terminal if you run the app with the command `io.github.realmazharhussain.GdmSettings -v`?

**Comment by mystrdat** [comment]
```
INFO: Application Version    = 1.1
INFO: Operating System       = Fedora Linux 37.20221101.n.0 (Silverblue)
INFO: PackageType            = Flatpak
INFO: TEMP_DIR               = /run/user/1000/app/io.github.realmazharhussain.GdmSettings
INFO: HOST_DATA_DIRS         = /usr/local/share:/usr/share
INFO: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO: UbuntuGdmGresourceFile = None
INFO: pkexec version 121
```

**Comment by realmazharhussain** [comment]
@mystrdat, What is the output of the following command?

```bash
sudo ls ~gdm/.config/monitors.xml
```

**Comment by mystrdat** [comment]
`/var/lib/gdm/.config/monitors.xml`

**Comment by realmazharhussain** [comment]
@mystrdat, it seems like your issue is with the GDM package and different from @remidebette's original issue but we won't know for sure before he responds.

Unless `/var/lib/gdm/.config/monitors.xml` file broken. Can you check that file or upload its contents here?

**Comment by mystrdat** [comment]
0 bytes, nothing in it.

**Comment by realmazharhussain** [comment]
And `~/.config/monitors.xml` does not exist?

**Comment by mystrdat** [comment]
It does

```
<monitors version="2">
  <configuration>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>DP-3</connector>
          <vendor>IVM</vendor>
          <product>PL3266Q</product>
          <serial>0x000002e0</serial>
        </monitorspec>
        <mode>
          <width>2560</width>
          <height>1440</height>
          <rate>143.912</rate>
        </mode>
      </monitor>
    </logicalmonitor>
  </configuration>
  <configuration>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>DP-3</connector>
          <vendor>IVM</vendor>
          <product>PL3266Q</product>
          <serial>0x000002e0</serial>
        </monitorspec>
        <mode>
          <width>2560</width>
          <height>1440</height>
          <rate>143.912</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <disabled>
      <monitorspec>
        <connector>HDMI-1</connector>
        <vendor>MEI</vendor>
        <product>Panasonic-TV</product>
        <serial>0x01010101</serial>
      </monitorspec>
    </disabled>
  </configuration>
  <configuration>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>DisplayPort-2</connector>
          <vendor>IVM</vendor>
          <product>PL3266Q</product>
          <serial>0x000002e0</serial>
        </monitorspec>
        <mode>
          <width>2560</width>
          <height>1440</height>
          <rate>143.912</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <disabled>
      <monitorspec>
        <connector>HDMI-A-0</connector>
        <vendor>MEI</vendor>
        <product>Panasonic-TV</product>
        <serial>0x01010101</serial>
      </monitorspec>
    </disabled>
  </configuration>
```

**Comment by realmazharhussain** [comment]
What is the output of the following commands?

```bash
flatpak run --command=sh io.github.realmazharhussain.GdmSettings
file $XDG_CONFIG_HOME/monitors.xml
exit
```

**Comment by remidebette** [comment]
Sorry, I had mistyped gdm3 for gdm in the reported folder structures, I just edited them.

So I just removed my file `~/.config/monitors.xml` to replicate the initial situation nd Launch the app with:

```bash
flatpak run io.github.realmazharhussain.GdmSettings -v
```

It gives me the following logs after clicking on the Display > "Apply current display settings"  button

```
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
INFO: Application Version    = 1.1
INFO: Operating System       = Ubuntu 22.04.1 LTS
INFO: PackageType            = Flatpak
INFO: TEMP_DIR               = /run/user/1000/app/io.github.realmazharhussain.GdmSettings
INFO: HOST_DATA_DIRS         = /usr/local/share:/usr/share
INFO: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO: UbuntuGdmGresourceFile = /usr/share/gnome-shell/gdm-theme.gresource
INFO: pkexec version 0.105
INFO: GLib 2.74.0
Connected to the local host. Press ^] three times within 1s to exit session.

Connection to the local host terminated.
```

And indeed the generated `/var/lib/gdm3/.config/monitors.xml` is created with 0 bytes

**Comment by remidebette** [comment]
Oh actually I also get 0 bytes when there is a file, I guess it only ever worked once manually copied.

```bash
❯ flatpak run --command=sh io.github.realmazharhussain.GdmSettings
[📦 io.github.realmazharhussain.GdmSettings ~]$ file $XDG_CONFIG_HOME/monitors.xml
/home/remi/.var/app/io.github.realmazharhussain.GdmSettings/config/monitors.xml: ASCII text
[📦 io.github.realmazharhussain.GdmSettings ~]$ exit
exit


```

**Comment by mystrdat** [comment]
Same

```
flatpak run --command=sh io.github.realmazharhussain.GdmSettings
[📦 io.github.realmazharhussain.GdmSettings ~]$ file $XDG_CONFIG_HOME/monitors.xml
/var/home/mystrdat/.var/app/io.github.realmazharhussain.GdmSettings/config/monitors.xml: ASCII text
```

**Comment by mystrdat** [comment]
`.rw-r--r--.`

**Comment by Pheggas** [comment]
I'm getting the same issue. Fedora 36 (Workstation Edition) Gnome 42.5 / Wayland.

**Comment by Pheggas** [comment]
> What are permissions on the file? (can be found with `ls -l ~/.config/monitors.xml` command)

On my particular machine those are -rw-r--r--

**Comment by realmazharhussain** [comment]
Let me get this straight.

- "Apply Current Display Settings" does not work but pretends to work in the UI
- Bug only occurs on fresh installs or when `~/.config/monitors.xml` is deleted
- The feature starts working properly once `~/.config/monitors.xml` is created
- Bug only occurs when using the app installed as a Flatpak (not as an AppImage or distro package)

Is that correct?

**Comment by remidebette** [comment]
All is correct except for point 2.
It never works, it always creates a 0 bytes file, as @mystrdat got me aware

My first thought was that if there is no file in the first place (fresh install) the user should at least be warned to take some action.

But also the 0bytes problem needs to be solved as well

**Comment by realmazharhussain** [comment]
> My first thought was that if there is no ~/.config/monitors.xml file in the first place (fresh install) the user should at least be warned to take some action.

This feature already exists but is not working for some reason. Following is a screenshot of this in action.

![Screenshot from 2022-11-05 12-15-31](https://user-images.githubusercontent.com/67191572/200107794-de87c04d-1da1-4cc6-9cff-17d28329fa0a.png)

**Comment by realmazharhussain** [comment]
I don't think it will make any difference but can you try the [latest beta](https://dl.flathub.org/beta-repo/appstream/io.github.realmazharhussain.GdmSettings.flatpakref) (currently v2.beta.0) and see if it also has the same issue?

**Comment by mystrdat** [comment]
> I thought point 2 and 3 were correct but they are not sufficient. It never works, it always creates a 0 bytes file, as @mystrdat got me aware
> 
> My first thought was that if there is no `~/.config/monitors.xml` file in the first place (fresh install) the user should at least be warned to take some action.
> 
> But also the 0bytes problem (most likely for flatpak) needs to be solved as well

This is correct, it never works. In my case I have previously manually copied monitors.xml to ~gdm before I used this software, may be directly related to that.

**Comment by remidebette** [comment]
If it helps, on my install the env var is not set:
```bash
❯ flatpak run --command=sh io.github.realmazharhussain.GdmSettings
[📦 io.github.realmazharhussain.GdmSettings ~]$ echo $XDG_CONFIG_HOME
/home/remi/.var/app/io.github.realmazharhussain.GdmSettings/config
[📦 io.github.realmazharhussain.GdmSettings ~]$ exit
exit

❯ echo $XDG_CONFIG_HOME

```

**Comment by remidebette** [comment]
By the way, I am not sure how it is supposed to work 
(I installed flatpak for this because I do not like not having a package manager and I do not see an apt repo)
but when I installed the app, it carried with it all these.

Is this required though? I already have GNOME with my ubuntu.

```bash
❯ flatpak history                                          
Time            Change         Application                                    Branch Installation Remote
Oct 16 19:48:27 add remote                                                           system       flathub
Oct 16 19:48:36 deploy install io.github.realmazharhussain.GdmSettings.Locale stable system       flathub
Oct 16 19:49:00 deploy install org.freedesktop.Platform.GL.default            22.08  system       flathub
Oct 16 19:49:01 deploy install org.freedesktop.Platform.openh264              2.2.0  system       flathub
Oct 16 19:49:03 deploy install org.gnome.Platform.Locale                      43     system       flathub
Oct 16 19:49:03 deploy install org.gtk.Gtk3theme.Yaru-dark                    3.22   system       flathub
Oct 16 19:51:00 deploy install org.gnome.Platform                             43     system       flathub
Oct 16 19:51:01 deploy install io.github.realmazharhussain.GdmSettings        stable system       flathub

```

**Comment by realmazharhussain** [comment]
> on my install the env var is not set

That is how most distros are configured. This is normal and expected.

> when I installed the app, it carried with it all these dependencies.
> 
> Is this required though? I already have GNOME with my ubuntu.

This is how flatpak works. What is happening is that

- You install `io.github.realmazharhussain.GdmSettings`
- It uses `org.gnome.Platform` and requires `io.github.realmazharhussain.GdmSettings.Locale` for localization support.
- `org.gnome.Platform` requires
  - `org.freedesktop.Platform.GL.default` (for hardware acceleration)
  - `org.freedesktop.Platform.openh264` (for h264 video codec)
  - `org.gnome.Platform.Locale` (for localization support)
- `org.gtk.Gtk3theme.Yaru-dark` is installed inside the flatpak because you were using yaru-dark gtk theme when installing/updating software using flatpak.

**Comment by realmazharhussain** [comment]
Guys, try the [latest beta](https://dl.flathub.org/beta-repo/appstream/io.github.realmazharhussain.GdmSettings.flatpakref).

**Comment by remidebette** [comment]
Hi @realmazharhussain 
I just installed the beta from the link you shared.

Whether or not the `~/.config/monitors.xml` file exists I get this:
![image](https://user-images.githubusercontent.com/16523229/200166592-bc1d88a9-4e38-408c-8272-3315e949d2ae.png)

```bash
❯ flatpak run io.github.realmazharhussain.GdmSettings -v
INFO :: Application Version    = 2.beta.0
INFO :: Operating System       = Ubuntu 22.04.1 LTS
INFO :: PackageType            = Flatpak
INFO :: TEMP_DIR               = /run/user/1000/app/io.github.realmazharhussain.GdmSettings
INFO :: HOST_DATA_DIRS         = /usr/local/share:/usr/share
INFO :: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO :: UbuntuGdmGresourceFile = /usr/share/gnome-shell/gdm-theme.gresource
INFO :: pkexec version 0.105
Connected to the local host. Press ^] three times within 1s to exit session.
chown: invalid spec: ‘Debian-gdm:’

Connection to the local host terminated.


```

**Comment by realmazharhussain** [comment]
What is the output of the following command?

```bash
grep -i gdm /etc/passwd
```

**Comment by remidebette** [comment]
Here it is:
```bash
❯ grep -i gdm /etc/passwd
gdm:x:121:127:Gnome Display Manager:/var/lib/gdm3:/bin/false
```

**Comment by realmazharhussain** [comment]
I have fixed the issue. The fix will be included in the next beta release (v2.beta.1).

In the meantime, you can install [this flatpak](https://github.com/realmazharhussain/gdm-settings/files/9983194/gdm-settings.flatpak.zip).

**Comment by remidebette** [comment]
Hi @realmazharhussain 

Indeed it works! Thank you
One minor thing is that if the file is not detected, the error pop up will remain until GdmSettings is restarted, even if the file is created in the meantime

**Comment by realmazharhussain** [comment]
> the error pop up will remain on every apply until GdmSettings is restarted, even if the file is created in the meantime.

That seems like an issue on the flatpak side.
