### ISSUE TITLE
[Portage support] Gentoo & derivatives support.

### ISSUE THREAD

**Issue by Loatchi** [realmazharhussain/gdm-settings#134]
### Description

Hello and thanks to the entire team working on this awesome project !

I've created an ebuild file for Portage (Gentoo's package manager) to handle your application. It would be nice to add it to the install field so that every distro based on Gentoo could benefit of it !

I've looked at other portage overlays and did not find your project whatsoever. If anyone here has the portage package manager it could be nice to give feedback on [gnome-extra/gdm-settings-1.1.ebuild](https://github.com/Loatchi/loatchi-overlay/blob/main/gnome-extra/gdm-settings/gdm-settings-1.1.ebuild). 

_The portage overlay:_ [loatchi-overlay](https://github.com/Loatchi/loatchi-overlay)

_We can absolutely discuss on how to implement such changes._ 

Thank you, Loatchi.

**Comment by Loatchi** [comment]
Sorry for late answer :/

I've added 2.0 properly. I just wanted to know how I could edit the wiki (or get the wiki edited to add my contribution) as I am not really into Github...

**Comment by realmazharhussain** [comment]
If you like, you can write the instructions here and I will add them to the wiki.

**Comment by Loatchi** [comment]
## Gentoo Linux

This app is available in [loatchi-overlay](https://github.com/Loatchi/loatchi-overlay).
To add the overlay:
```bash
eselect repository add loatchi git https://github.com/Loatchi/loatchi-overlay.git
emaint sync -r loatchi
```
To actually install gdm-settings:
```bash
emerge gdm-settings
```

**Comment by realmazharhussain** [comment]
I have added the install instructions for Gentoo to the wiki.
