### ISSUE TITLE
Can't apply display settings

### ISSUE THREAD

**Issue by rockerbacon** [realmazharhussain/gdm-settings#135]
### What happened?

Applying display settings doesn't work. After logout and cold reboot, GDM still uses its seemingly random settings.

Tried both on Xorg and Wayland sessions and neither worked.

### Expected behavior

GDM should use the current user's display settings after applying them through gdm-settings.

### To Reproduce

1. Configure the desired display settings using the GNOME settings app;
2. Open gdm-settings and head to the display tab;
3. Click on the "Apply" button beside "Apply current display settings";
4. Input admin user password and confirm;
5. Click on "Apply" at the window title bar;
6. Input admin user password and confirm;
7. Confirm logout when prompted;

### Application Version

v1.1

### Format/Source

Flatpak

### Environment

- **OS**: Fedora 37 (Workstation Edition)
- **GNOME**: 43.1

**Comment by realmazharhussain** [comment]
Have you tried the latest beta version?

**Comment by arthurbg951** [comment]
Similar problem here! OS: fedora 37. GNOME: 43.2.

I've changed cursor theme and mouse speed. Cursor speed aparently worked well, but cursor theme does not have be applyed.

I've tested [the latest beta version](https://dl.flathub.org/beta-repo/appstream/io.github.realmazharhussain.GdmSettings.flatpakref) as you mensioned before and stable release at this moment on flathub.

**Comment by realmazharhussain** [comment]
That is an entirely different problem and may have to do something with file permissions.

Please, open a new issue if you would like to help in investigating and fixing the problem.
