### ISSUE TITLE
Importing settings via dconf not working

### ISSUE THREAD

**Issue by TechXero** [realmazharhussain/gdm-settings#139]
### What happened?

settings not getting applied if imported via dconf load

Is there no way to apply my settings by default ?

### Expected behavior

Well, for it to work...

### To Reproduce

Run below command log out (already exported my settings)
```
dconf load /io/github/realmazharhussain/GdmSettings/ < /etc/skel/.config/xgdm.conf
```

### Detailed Explanation (Optional)

I maintain an Arch Based Distro using KDE for now, with a Gnome edition coming soon, importing settings don't apply unless I load the app n hit apply then input my admin pass.

### Application Version

2.0

### Format/Source

AUR

### Environment

- **OS**: ArchLinux [XeroLinux](https://xerolinux.xyz)
- **GNOME**:  43.2

**Comment by realmazharhussain** [comment]
Settings in the `/io/github/realmazharhussain/GdmSettings/` dconf path are just for the app to remember user's preferences. They do not affect GDM itself at all.

Due to technical reasons, It is required to open the app and apply the settings from there.

**Comment by realmazharhussain** [comment]
An example override file can be found [here](https://github.com/realmazharhussain/manjaro-iso-profiles/raw/f5e31ea7fd59c698e30b72cccec4a0d2e3379d93/community/gnome-vanilla/desktop-overlay/usr/share/glib-2.0/schemas/99-sane-settings.gschema.override).

**Comment by TechXero** [comment]
Will try that thanks my friend. Happy Holidays btw ;)
