### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by Vistaus** [realmazharhussain/gdm-settings#14]
Thank you for making this great and much needed app! 🙂

It would be great if you could implement translation support. When implemented, I will provide the Dutch translation. 🙂

**Comment by realmazharhussain** [comment]
I am very new to App Development. This is my first real App. I do not where to start to add translation support. I'm not saying it's hard. I just haven't tried. Any way, I will just have to read about this topic.

That being said, I would love for this app to have translations and I do plan on adding translation support in future (near future hopefully).

**Comment by realmazharhussain** [comment]
Translation support has been added to the application. Instructions on how to translate can be found [here](https://github.com/realmazharhussain/gdm-settings/blob/main/docs/translate.md).

**Note:** There seems to be a bug in GTK4 (the graphics/widget library this app uses) where only a small number of translations show up when running the application. Remaining text shows up in English even if its translation was provided.
**But** translators can start translating the app and when this bug gets fixed, the translations will automatically start working.

**Comment by Vistaus** [comment]
Thank fou for adding translation support! I'll start translating right away! 🙂

**Comment by realmazharhussain** [comment]
You are welcome
