### ISSUE TITLE
Unable to apply current display settings

### ISSUE THREAD

**Issue by Angelsen** [realmazharhussain/gdm-settings#143]
### What happened?

Hi! I'm unable to apply current display settings.

```
gdm-settings -v
INFO: Application Version    = 2.0
INFO: Operating System       = Manjaro Linux
INFO: PackageType            = Unknown
INFO: TEMP_DIR               = /run/user/1000/app/io.github.realmazharhussain.GdmSettings
INFO: HOST_DATA_DIRS         = /usr/local/share:/usr/share
INFO: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO: UbuntuGdmGresourceFile = None
INFO: pkexec version 122
DEBUG: No such file or directory: '/run/user/1000/app/io.github.realmazharhussain.GdmSettings/monitors.xml'
```

![image](https://user-images.githubusercontent.com/15813633/210666772-20e642dd-7e2c-4b43-b8e5-61de3a10c596.png)

### Expected behavior

Apply current display settings to GDM settings.

### To Reproduce

Click on apply current display settings. 

### Detailed Explanation (Optional)

> $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME /. config should be used. $XDG_STATE_HOME defines the base directory relative to which user-specific state files should be stored.

My monitors.xml is stored in  $HOME /.config, might be a couse?

### Application Version

2.0

### Format/Source

AUR (gdm-settings)

### Environment

- **OS**: Manjaro Linux 22.0.0
- **GNOME**: 43.2

**Comment by realmazharhussain** [comment]
Is `monitors.xml` an empty file or does it have any contents?

Also, did you follow the instructions stated in the error dialog?

**Comment by yuezhihan** [comment]
Same issue here. My monitors.xml is indeed stored in ~/.config. However, the $XDG_CONFIG_HOME is not defined in the system.

However, I can manually apply the monitor settings by `sudo cp ~/.config/monitors.xml /var/lib/gdm3/.config`.

According to [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/):
> If $XDG_CONFIG_HOME is either not set or empty, a default equal to  $HOME/.config should be used.

I guess gdm-settings hasn't set the default value according to this rule.

**Comment by realmazharhussain** [comment]
@yuezhihan Are you using Flatpak version of the app?

**Comment by yuezhihan** [comment]
> @yuezhihan Are you using Flatpak version of the app?

I'm using the latest AppImage version.

**Comment by realmazharhussain** [comment]
That is strange.

I'll work on a debug version of the AppImage and I'll post it here. But it will take some time.

**Comment by realmazharhussain** [comment]
Here are packages with the bug fixed.

[gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/10526659/gdm-settings.flatpak.zip)  
[Login_Manager_Settings.AppImage](https://mega.nz/file/ywFinYRY#E-gp_QoEeHWjhDf0hxTuYXJ1c-GboNNFeIf9jnJvwHo)

If the problem doesn't seem to be solved, feel free to reopen the issue.
