### ISSUE TITLE
Option that allow/support the scaling for HiDPI and login screen.

### ISSUE THREAD

**Issue by Tuxman2** [realmazharhussain/gdm-settings#151]
### Description

Hello,

I would like to see an option that would set or enable scaling for the login screen (GDM), and devices with a small screen size (example: 11.6"). For now, this should be done manually and via the command line.

Otherwise, thank you very much for your work.

Regards.

**Comment by realmazharhussain** [comment]
![screenshot-6](https://user-images.githubusercontent.com/67191572/223110896-7999072c-f893-49b3-9233-924472d7ffa3.png)

**Comment by PhilDevProg** [comment]
@realmazharhussain That option doesn't apply the monitor scaling...

**Comment by realmazharhussain** [comment]
It is supposed to.

However, you may need to log in to a Wayland session and change & apply monitor settings from the GNOME "Settings" app first before clicking that button in GDM Settings.

**Comment by PhilDevProg** [comment]
100% and 200% scaling works but fractional scaling doesn't...

**Comment by realmazharhussain** [comment]
Does fractional scaling work inside GNOME itself?

**Comment by PhilDevProg** [comment]
Yes, btw I'm using Wayland.
