### ISSUE TITLE
Disabling user list prevents login

### ISSUE THREAD

**Issue by PhilDevProg** [realmazharhussain/gdm-settings#156]
### What happened?

After I enabled the option of disabling the user list and rebooted, I wasn't able to login anymore. It would just say that the password legitimation failed and I had to reset the configuration via tty.

### Expected behavior

Being able to login normally.

### To Reproduce

1) Enable option in login screen 'Disable user list'
2) Reboot
3) Experience problem

### Application Version

2.1

### Format/Source

Flatpak

### Environment

- **OS**: Fedora 37
- **GNOME**: 43.3

**Comment by realmazharhussain** [comment]
Instead of using the app to disable user list, if you do that manually with the following commands, does the problem still occur?

```bash
echo -e '[org/gnome/login-screen]\ndisable-user-list=true' | sudo tee /etc/dconf/db/gdm.d/99-disable-user-list
sudo dconf update
```

**Comment by PhilDevProg** [comment]
Yes

**Comment by realmazharhussain** [comment]
That seems like an issue with GDM itself.
