### ISSUE TITLE
[FEATURE] Disable mouse acceleration

### ISSUE THREAD

**Issue by Devorlon** [realmazharhussain/gdm-settings#19]
### Description

An option to disable mouse acceleration / change the sensitivity of the cursor.

**Comment by realmazharhussain** [comment]
I'll look into it

**Comment by realmazharhussain** [comment]
Mouse settings have been added to the application.

**Comment by Devorlon** [comment]
Just installed and tested, it works perfectly. Thanks

**Comment by realmazharhussain** [comment]
You are welcome.
