### ISSUE TITLE
Can't change display resolution

### ISSUE THREAD

**Issue by FrancoisSevestre** [realmazharhussain/gdm-settings#2]
There is no option to change display resolution.

**Comment by realmazharhussain** [comment]
I'll look into that.

**Comment by anthr76** [comment]
This might be a tricky one to solve but I can very much benefit from a resolution setter and screen chooser. Usually have multiple displays gdm always ends up on the wrong screen and I need to go and change the monitors.xml or something as such..

**Comment by realmazharhussain** [comment]
A button that applies current display settings (including resolution) to GDM has been added in the new 'Tools' page of the app.

Test it out and let me know if it works for you.

**Comment by FrancoisSevestre** [comment]
Works fine!
