### ISSUE TITLE
Cannot compile on Debian 11?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [realmazharhussain/gdm-settings#20]
Cannot compile on Debian 11?

# /usr/local/bin/meson build
The Meson build system
Version: 0.62.0
Source dir: /usr/local/bin/gdm-settings
Build dir: /usr/local/bin/gdm-settings/build
Build type: native build
Project name: gdm-settings
Project version: 0.4
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency pygobject-3.0 found: YES 3.38.0
Found CMake: /usr/bin/cmake (3.18.4)
Run-time dependency libadwaita-1 found: NO (tried pkgconfig and cmake)

meson.build:7:0: ERROR: Dependency "libadwaita-1" not found, tried pkgconfig and cmake

A full log can be found at /usr/local/bin/gdm-settings/build/meson-logs/meson-log.txt

**Comment by realmazharhussain** [comment]
Sorry for the inconvenience but Debian 11 is not supported **YET** and may never be supported directly (because it doesn't have a lot of the dependencies for this app).

A flatpak and a ***proper*** AppImage are in the works. They should support Debian 11 and other non-bleeding-edge distributions.

**Comment by Jibun-no-Kage** [comment]
Yup, I realized after opening the issue, that one of the key dependencies is only going to be in Debian 11, which is only now moving into initial testing phase.  Thanks for the quick reply, none the less.  Glad this solution is proactively supported.

**Comment by realmazharhussain** [comment]
A proper AppImage and a Flatpak are available now.
