### ISSUE TITLE
Fedora not booting after changing the login background color

### ISSUE THREAD

**Issue by edwardally** [realmazharhussain/gdm-settings#29]
Hi,

I'm using latest Fedora 35 Workstation and install flatpak version from [this](https://github.com/realmazharhussain/gdm-settings/issues/8) post and it end up hang with a black screen.

I also did run the command as suggested `sudo mv /usr/share/gnome-shell/gnome-shell-theme.gresource{.default,}` and it return error saying no directory or something with no luck.

** I"m sorry that I only have 1 notebook with dual boot so I might have some trouble or I will try my best to copy the output exactly  from the screen. 

Thanks

**Comment by realmazharhussain** [comment]
To temporarily fix the issue reinstall the GNOME Shell with

```bash
dnf reinstall gnome-shell
```

Then, run this application again using the terminal (you can do so by running the command `flatpak run io.github.realmazharhussain.GdmSettings` in the terminal) and apply your settings. If there's any output on the terminal, provide it here. Also provide the following files here (after applying the settings);

```
/usr/share/gnome-shell/gnome-shell-theme.gresource
/etc/dconf/db/gdm.d/*
/etc/dconf/profile/gdm
```

**Comment by edwardally** [comment]
No output from the terminal after running `flatpak run io.github.realmazharhussain.GdmSettings`

[Before.zip](https://github.com/realmazharhussain/gdm-settings/files/8495987/file.zip)

---------

After applied 
> saving default theme ...
cp: cannot stat '/var/run/host/usr/share/gnome-shell/gnome-shell-theme.gresource': No such file or directory

[After.zip](https://github.com/realmazharhussain/gdm-settings/files/8496007/After.zip)

**Comment by realmazharhussain** [comment]
Try this updated flatpak; [gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/8499327/gdm-settings.flatpak.zip)

**Comment by edwardally** [comment]
Same result unable to boot up after applying the setting

**Comment by realmazharhussain** [comment]
I have created a shell script for you.

- First, make sure your gnome-shell is up to date.
- Then download the latest gnome-shell rpm
- Then apply settings from this application.
- After applying, run the script with path to the rpm as first argument.
- Post its output here along with the files it described as modified.

The script will be uploaded here shortly.

**Comment by edwardally** [comment]
Sorry I"m newbie for Linux world. 

What do you mean path to the RPM? and where is the path?

**Comment by realmazharhussain** [comment]
No need to be sorry.

Path means location of a file or folder.

For example, `/home/mazhar/Downloads` or `~/Downloads` is path to my Downloads folder.

Once you have downloaded gnome-shell rpm file, when running the script, you need to tell it where that rpm file is. So that the script can check it against your system and report the differences.

**Comment by edwardally** [comment]
Hi,

This command `dnf --downloadonly install gnome-shell` doesn't download or update any file so I download the gnome-shell rpm using `dnf download  gnome-shell` and it downloaded the file `gnome-shell-41.4-1.fc35.x86_64.rpm` in `/home/hm025/Downloads/script-1/`

Then I try issue the following command in `/home/hm025/Downloads/script-1/` (Where the script located)
`./check-gnome-shell.sh /home/hm025/Downloads/script-1/gnome-shell-41.4-1.fc35.x86_64.rpm`
and
`./check-gnome-shell.sh /home/hm025/Downloads/script-1/`

and it keep asking me for `Plz! provide a 'gnome-shell' rpm`

**Comment by realmazharhussain** [comment]
Sorry! My bad.

If `check-gnome-shell.sh` and `gnome-shell-41.4-1.fc35.x86_64.rpm` are in the same folder, you can run the script this way

```bash
./check-gnome-shell.sh gnome-shell-41.4-1.fc35.x86_64.rpm
```

This should work.

**Comment by realmazharhussain** [comment]
If that doesn't work, here is an updated version of the script;

[script-2.zip](https://github.com/realmazharhussain/gdm-settings/files/8526963/script-2.zip)

**Comment by edwardally** [comment]
![image](https://user-images.githubusercontent.com/1024003/164431349-01b5d3d3-bb6b-483a-93b9-677c416faacb.png)

Above is the log after appied script2

**Comment by realmazharhussain** [comment]
Try this script;

[script.zip](https://github.com/realmazharhussain/gdm-settings/files/8530043/script.zip)

**Comment by realmazharhussain** [comment]
Also;

uninstall previously installed flatpak and install this one

[gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/8530078/gdm-settings.flatpak.zip)

**Comment by edwardally** [comment]
![image](https://user-images.githubusercontent.com/1024003/164616924-7314c1c3-617a-49d9-b2eb-b959629eaee0.png)

Using latest script and flatpak

**Comment by realmazharhussain** [comment]
I've updated the flatpak and the script again. Try the new ones.

[gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/8542709/gdm-settings.flatpak.zip)
[script.zip](https://github.com/realmazharhussain/gdm-settings/files/8542710/script.zip)

**Comment by realmazharhussain** [comment]
Bug #35 might have something to do with this. Just fixed it. Here is the new flatpak;

[gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/8549130/gdm-settings.flatpak.zip)

**Comment by Cherro59** [comment]
Have such problem also on fedora 35. Used flatpak from comment above. On display appear white screen with screen "Something is broken". Gnome reinstall helped

**Comment by edwardally** [comment]
The latest script and flatpak still not luck

![image](https://user-images.githubusercontent.com/1024003/165004004-75101b35-6b56-4480-b38c-66b64f86754c.png)

**Comment by realmazharhussain** [comment]
You need to install `zstd` for the script to work properly.

**Comment by realmazharhussain** [comment]
What is the output if you run the following commands

```bash
rpm2cpio gnome-shell-41.4-1.fc35-x86_64.rpm > gnome-shell.cpio
file gnome-shell.cpio
```

**Comment by realmazharhussain** [comment]
Previously, when you ran the command

```bash
flatpak run io.github.realmazharhussain.GdmSettings
```

it printed the following line

```
cp: cannot stat '/var/run/host/usr/share/gnome-shell/gnome-shell-theme.gresource': No such file or directory
```

Does it still output that line?

**Comment by edwardally** [comment]
1: Output
![image](https://user-images.githubusercontent.com/1024003/165194768-a6dca562-5f85-4b59-b745-24e56ebf12c9.png)
[gnome-shell.zip](https://github.com/realmazharhussain/gdm-settings/files/8558745/gnome-shell.zip)

2: Output
![image](https://user-images.githubusercontent.com/1024003/165195078-7622d2e9-c8cc-47b7-bef5-2b076eb73ff6.png)

No other error - Only single line msg "Saving default them" for the 1st run

**Comment by realmazharhussain** [comment]
Try this updated script. I'm pretty sure it will work this time.

[script.zip](https://github.com/realmazharhussain/gdm-settings/files/8562365/script.zip)

**Comment by edwardally** [comment]
The script is ok
![image](https://user-images.githubusercontent.com/1024003/165411353-0318d865-c2c6-4113-9f4b-0b04c83ab6a2.png)
[gnome-shell-theme.zip](https://github.com/realmazharhussain/gdm-settings/files/8567574/gnome-shell-theme.zip)

**Comment by realmazharhussain** [comment]
Try this flatpak;

[gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/8580115/gdm-settings.flatpak.zip)

**Comment by Cherro59** [comment]
![изображение](https://user-images.githubusercontent.com/73524699/165741493-91c1565f-1358-495c-ab0c-9e02559f1850.png)
 It cant find some file for some reason. Latest flatpak from post above

**Comment by Cherro59** [comment]
No issues in terminal but GNOME(42) crashed and again not working gdm.

**Comment by realmazharhussain** [comment]
@Cherro59, could you post the logs here?

**Comment by Alvimm** [comment]
![IMG_20220513_002756481.jpg](https://user-images.githubusercontent.com/92137207/168205795-c06a31c1-f14c-4f21-a7ef-4d3e9b437d5f.jpg)

I had this issue after installing the gdm settings and rebooting my system, I'm using the fedora 36 workstation. Please help me, I'm a newbie too!

**Comment by realmazharhussain** [comment]
@Alvimm, it's gonna be a while before this issue gets fixed.

Do not use this application before this issue gets fixed.

## To fix the issue and restore previous settings,
1. While on that white error screen, press `Ctrl`+`F2`.

   You will be presented with a full screen terminal (also known as a TTY).
2. Enter your username and password in order to log in to the TTY.
3. Run the following commands in the TTY (in order to reset everything changed by the application),

   ```bash
   sudo mv -f /usr/share/gnome-shell/gnome-shell-theme.gresource{.default,}
   sudo rm -rf /etc/dconf/db/gdm.d/95-gdm-settings
   sudo dconf update
   ```
4. Run the following command to reboot
   ```bash
   systemctl reboot
   ```
   Or
   ```bash
   sudo reboot
   ```

**Comment by Alvimm** [comment]
Thanks for the help!

**Comment by Alvimm** [comment]
Yes, i did it! Thanks!

**Comment by realmazharhussain** [comment]
I have changed some things in the app.

Here are new packages;
- [AppImage](https://github.com/realmazharhussain/gdm-settings/files/8747457/gdm-settings.AppImage.zip)
- [Flatpak](https://github.com/realmazharhussain/gdm-settings/files/8747458/gdm-settings.flatpak.zip)

You can install any of the above packages or install the app from source and check if it still breaks GDM.

**Comment by Truemmerer** [comment]
The new version does not work for me yet.
It still breaks GDM.
```
gdm[2707]: Gdm: GdmDisplay: Session never registered, failing
gdm[2707]: GLib: g_propagate_error: assertion 'src != NULL' failed
gdm[2707]: GLib: g_propagate_error: assertion 'src != NULL' failed
gdm[2707]: GLib: g_propagate_error: assertion 'src != NULL' failed
gdm[2707]: GLib: g_propagate_error: assertion 'src != NULL' failed
gdm[2707]: GLib: g_propagate_error: assertion 'src != NULL' failed
gdm[2707]: GLib: g_propagate_error: assertion 'src != NULL' failed
gdm[2707]: GLib: g_propagate_error: assertion 'src != NULL' failed
gdm[2707]: GLib: g_propagate_error: assertion 'src != NULL' failed
gdm[2707]: GLib: g_propagate_error: assertion 'src != NULL' failed
gdm[2707]: GLib: g_propagate_error: assertion 'src != NULL' failed
gdm[2707]: GLib: g_propagate_error: assertion 'src != NULL' failed
gdm[2707]: Gdm: GdmDisplay: Session never registered, failing
gdm-launch-environment][2814]: GLib: g_propagate_error: assertion 'src != NULL' failed
```

**Comment by stefanmaric** [comment]
I downloaded and installed the Flatpak version and still getting the same error:

```shell
may 23 12:55:22 fedora gnome-session[19523]: gnome-session-binary[19523]: GLib-GIO-CRITICAL: g_bus_get_sync: assertion 'error == NULL || *error == NULL' failed
may 23 12:55:22 fedora gnome-session[19523]: gnome-session-binary[19523]: GLib-GIO-CRITICAL: g_bus_get_sync: assertion 'error == NULL || *error == NULL' failed
may 23 12:55:22 fedora gnome-session-binary[19523]: GLib-GIO-CRITICAL: g_bus_get_sync: assertion 'error == NULL || *error == NULL' failed
may 23 12:55:22 fedora gnome-session-binary[19523]: GLib-GIO-CRITICAL: g_bus_get_sync: assertion 'error == NULL || *error == NULL' failed
may 23 12:55:22 fedora gnome-shell[19555]: Running GNOME Shell (using mutter 42.1) as a X11 window and compositing manager
may 23 12:55:22 fedora /usr/libexec/gdm-x-session[19502]: (II) modeset(0): EDID vendor "SHP", prod id 5182
may 23 12:55:22 fedora /usr/libexec/gdm-x-session[19502]: (II) modeset(0): Printing DDC gathered Modelines:
may 23 12:55:22 fedora /usr/libexec/gdm-x-session[19502]: (II) modeset(0): Modeline "3840x2160"x0.0  533.25  3840 3888 3920 4000  2160 2163 2168 2222 -hsync -vsync (133.3 kHz eP)
may 23 12:55:22 fedora gnome-shell[19555]: ATK Bridge is disabled but a11y has already been enabled.
may 23 12:55:22 fedora audit[19555]: AVC avc:  denied  { map } for  pid=19555 comm="gnome-shell" path="/usr/share/gnome-shell/gnome-shell-theme.gresource" dev="dm-0" ino=706967 scontext=system_u:system_r:xdm_t:s0-s0:c0.c1023 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=0
may 23 12:55:22 fedora gnome-shell[19555]: JS ERROR: GLib.FileError: Failed to map /usr/share/gnome-shell/gnome-shell-theme.gresource' /usr/share/gnome-shell/gnome-shell-theme.gresource': mmap() failed: Permission denied
                                           reloadThemeResource@resource:///org/gnome/shell/ui/main.js:441:35
                                           _initializeUI@resource:///org/gnome/shell/ui/main.js:193:5
                                           start@resource:///org/gnome/shell/ui/main.js:166:5
                                           @resource:///org/gnome/shell/ui/init.js:6:17
may 23 12:55:22 fedora gnome-shell[19555]: Execution of main.js threw exception: Module resource:///org/gnome/shell/ui/init.js threw an exception
may 23 12:55:22 fedora gnome-session[19523]: gnome-session-binary[19523]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
may 23 12:55:22 fedora gnome-session-binary[19523]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
may 23 12:55:22 fedora gnome-shell[19588]: Running GNOME Shell (using mutter 42.1) as a X11 window and compositing manager
may 23 12:55:22 fedora /usr/libexec/gdm-x-session[19502]: (II) modeset(0): EDID vendor "SHP", prod id 5182
may 23 12:55:22 fedora /usr/libexec/gdm-x-session[19502]: (II) modeset(0): Printing DDC gathered Modelines:
may 23 12:55:22 fedora /usr/libexec/gdm-x-session[19502]: (II) modeset(0): Modeline "3840x2160"x0.0  533.25  3840 3888 3920 4000  2160 2163 2168 2222 -hsync -vsync (133.3 kHz eP)
may 23 12:55:22 fedora gnome-shell[19588]: ATK Bridge is disabled but a11y has already been enabled.
may 23 12:55:23 fedora audit[19588]: AVC avc:  denied  { map } for  pid=19588 comm="gnome-shell" path="/usr/share/gnome-shell/gnome-shell-theme.gresource" dev="dm-0" ino=706967 scontext=system_u:system_r:xdm_t:s0-s0:c0.c1023 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=0
may 23 12:55:23 fedora gnome-shell[19588]: JS ERROR: GLib.FileError: Failed to map /usr/share/gnome-shell/gnome-shell-theme.gresource' /usr/share/gnome-shell/gnome-shell-theme.gresource': mmap() failed: Permission denied
                                           reloadThemeResource@resource:///org/gnome/shell/ui/main.js:441:35
                                           _initializeUI@resource:///org/gnome/shell/ui/main.js:193:5
                                           start@resource:///org/gnome/shell/ui/main.js:166:5
                                           @resource:///org/gnome/shell/ui/init.js:6:17
may 23 12:55:23 fedora gnome-shell[19588]: Execution of main.js threw exception: Module resource:///org/gnome/shell/ui/init.js threw an exception
may 23 12:55:23 fedora gnome-session[19523]: gnome-session-binary[19523]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
may 23 12:55:23 fedora gnome-session[19523]: gnome-session-binary[19523]: WARNING: App 'org.gnome.Shell.desktop' respawning too quickly
may 23 12:55:23 fedora gnome-session-binary[19523]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
may 23 12:55:23 fedora gnome-session-binary[19523]: WARNING: App 'org.gnome.Shell.desktop' respawning too quickly
may 23 12:55:23 fedora gnome-session-binary[19523]: Unrecoverable failure in required component org.gnome.Shell.desktop
```

I am still baffled by the "permissions" part, because the file descriptors for such file are the same before and after applying the gdm settings and before and after restoring it with `sudo dnf reinstall gnome-shell`. :thinking:

**Comment by stefanmaric** [comment]
For reference, this is what I get before applying changes with `gdm-settings` (Flatpak preview version):

```shell
$ sudo ls -l /usr/share/gnome-shell/gnome-shell-theme.gresource
-rw-r--r--. 1 root root 327345 may 19 19:41 /usr/share/gnome-shell/gnome-shell-theme.gresource

$ sudo lsattr /usr/share/gnome-shell/gnome-shell-theme.gresource
---------------------- /usr/share/gnome-shell/gnome-shell-theme.gresource
```

And this is what I get after:

```shell
$ sudo ls -l /usr/share/gnome-shell/gnome-shell-theme.gresource
-rw-r--r--. 1 root root 513167 may 23 13:17 /usr/share/gnome-shell/gnome-shell-theme.gresource

$ sudo lsattr /usr/share/gnome-shell/gnome-shell-theme.gresource
---------------------- /usr/share/gnome-shell/gnome-shell-theme.gresource
```

**Comment by arun54321** [comment]
selinux of gresource is changed after using login-manager still it does not crash.
 before: `system_u:object_r:usr_t:s0 /usr/share/gnome-shell/gnome-shell-theme.gresource`
 after: `unconfined_u:object_r:cache_home_t:s0 /usr/share/gnome-shell/gnome-shell-theme.gresource
`

**Comment by realmazharhussain** [comment]
@arun54321 What is SELinux status of your installation? You can check it by running `setstatus` command without any arguments.

**Comment by arun54321** [comment]
$getenforce
`Enforcing`

**Comment by realmazharhussain** [comment]
People whose GDM breaks, try these packages.

[gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/8767927/gdm-settings.flatpak.zip)
[gdm-settings.AppImage.zip](https://github.com/realmazharhussain/gdm-settings/files/8767926/gdm-settings.AppImage.zip)

Do these fix the issue?

**Comment by arun54321** [comment]
The command is sestatus. not se**t**status
~ ❯ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

**Comment by Cherro59** [comment]
Flatpak from above comletly broke my gnome-shell. On bar huge icons from high-contrast theme. I wanted to use new screenrecorder in gnome.Here no button to take a shot. Dash is really small also as a app menu
![изображение](https://user-images.githubusercontent.com/73524699/170188365-39cc1e6c-1ee7-426e-85b9-1609cf497b1a.png)

**Comment by realmazharhussain** [comment]
@Cherro59 Log out and Log in again

**Comment by Cherro59** [comment]
Already did. But its need to resolve. Newbie can think that his system is broken. OR affter settings apply there is needed force gnome restart

**Comment by realmazharhussain** [comment]
So it did get fixed after logging out and logging in?

**Comment by Cherro59** [comment]
Yes. I tried it again and there was nothing happened with gnome. I think there should be a line with label - "Try restart your session if GNOME changed theme". Now it's working as should be

**Comment by realmazharhussain** [comment]
> I think there should be a line with label - "Try restart your session if GNOME changed theme".

I will add that to planned features.

By the way, if user-theme extension is enabled, non-flatpak versions of the app do not let the above [problem](#issuecomment-1136751785) happen.

**Comment by PimpinPumpkin** [comment]
Just tested the latest Flatpak from this thread in a Fedora 36 Workstation virtual machine. It no longer breaks GDM! Gonna try this on my production rig now. I saw your Reddit thread by the way. I wish I saw this thread sooner though, because I didn't realize I could just reinstall Gnome to fix the white screen of death. Thanks for the great work sir :)

**Comment by realmazharhussain** [comment]
@PimpinPumpkin You are welcome.

**Comment by realmazharhussain** [comment]
@edwardally @Alvimm @Truemmerer @stefanmaric

Is it working for you too now?

Here are the links again
[gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/8767927/gdm-settings.flatpak.zip)
[gdm-settings.AppImage.zip](https://github.com/realmazharhussain/gdm-settings/files/8767926/gdm-settings.AppImage.zip)

**Comment by stefanmaric** [comment]
@realmazharhussain I clean-installed the latest flatpak you provided and this time gdm broke upon clicking APPLY (and entering my password). The only thing I changed in gdm-settings was the icon theme.

Here the crash report: https://retrace.fedoraproject.org/faf/reports/102070/

**Comment by realmazharhussain** [comment]
It seems like an issue in the GSettings(DConf) configuration created by this app. Could you send me the file `/etc/dconf/db/gdm.d/95-gdm-settings` present on your system?

**Comment by stefanmaric** [comment]
It is the only file I have in that folder:

```shell
cat /etc/dconf/db/gdm.d/95-gdm-settings 
#-------- Interface ---------
[org/gnome/desktop/interface]
#----------------------------
cursor-theme='Adwaita'
icon-theme='Papirus-Dark'
show-battery-percentage=true
clock-show-seconds=false
clock-show-weekday=false
clock-format='24h'
font-name='Sans 11'
font-antialiasing='grayscale'
font-hinting='slight'
text-scaling-factor=1.0

#-------- Sound ---------
[org/gnome/desktop/sound]
#------------------------
theme-name='freedesktop'
event-sounds=true
input-feedback-sounds=false
allow-volume-above-100-percent=false

#-------------- Mouse ---------------
[org/gnome/desktop/peripherals/mouse]
#------------------------------------
accel-profile='default'
natural-scroll=false
speed=0.35

#-------------- Touchpad ---------------
[org/gnome/desktop/peripherals/touchpad]
#---------------------------------------
speed=0.35
tap-to-click=true
natural-scroll=true
two-finger-scrolling-enabled=true
disable-while-typing=true

#------------- Night Light --------------
[org/gnome/settings-daemon/plugins/color]
#----------------------------------------
night-light-enabled=false
night-light-temperature=uint32 3000
night-light-schedule-automatic=true
night-light-schedule-from=19.0
night-light-schedule-to=6.0

#----- Login Screen ----
[org/gnome/login-screen]
#-----------------------
logo=''
banner-message-enable=false
banner-message-text='Welcome!'
disable-restart-buttons=false
disable-user-list=false
```

**Comment by realmazharhussain** [comment]
The `/etc/dconf/db/gdm.d/95-gdm-settings` file seems fine. Could you send me the output of `journalctl -b`?

Maybe, I could find something there.

**Comment by realmazharhussain** [comment]
Sorry! my internet plan ends now and I will not be available for the rest of the day. But I will be back tomorrow.

**Comment by sorcererinferior** [comment]
> To temporarily fix the issue reinstall the GNOME Shell with
> 
> ```shell
> dnf reinstall gnome-shell
> ```
> 
> Then, run this application again using the terminal (you can do so by running the command `flatpak run io.github.realmazharhussain.GdmSettings` in the terminal) and apply your settings. If there's any output on the terminal, provide it here. Also provide the following files here (after applying the settings);
> 
> ```
> /usr/share/gnome-shell/gnome-shell-theme.gresource
> /etc/dconf/db/gdm.d/*
> /etc/dconf/profile/gdm
> ```

I experienced a similar failure on Fedora 36 and your recommendation to `dnf reinstall gnome-shell` saved my pc.

**Comment by edwardally** [comment]
> @edwardally @Alvimm @Truemmerer @stefanmaric
> 
> Is it working for you too now?
> 
> Here are the links to the new packages again [gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/8767927/gdm-settings.flatpak.zip) [gdm-settings.AppImage.zip](https://github.com/realmazharhussain/gdm-settings/files/8767926/gdm-settings.AppImage.zip)
> 
> **Edit:** If you have previously installed the flatpak from Flathub, you will need to run the following command in order to run this version of the app instead of the one from Flathub.
> 
> ```shell
> flatpak run io.github.realmazharhussain.GdmSettings//master
> ```
> 
> Note the `//master` at the end of the command.

I'm away from my laptop. I will test it some time next week

**Comment by realmazharhussain** [comment]
> The `/etc/dconf/db/gdm.d/95-gdm-settings` file seems fine. Could you send me the output of `journalctl -b`?
> 
> Maybe, I could find something there.

@stefanmaric

**Comment by Nakamerica** [comment]
> To temporarily fix the issue reinstall the GNOME Shell with
> 
> ```shell
> dnf reinstall gnome-shell
> ```


Managed to come across this issue myself right now, Fedora 35 and Gnome 41.6 - using the flatpak version of this app. Thank you very much for the workaround.

**Comment by Truemmerer** [comment]
> @edwardally @Alvimm @Truemmerer @stefanmaric
> 
> Is it working for you too now?
> 
> Here are the links to the new packages again [gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/8767927/gdm-settings.flatpak.zip) [gdm-settings.AppImage.zip](https://github.com/realmazharhussain/gdm-settings/files/8767926/gdm-settings.AppImage.zip)
> 
> **Edit:** If you have previously installed the flatpak from Flathub, you will need to run the following command in order to run this version of the app instead of the one from Flathub.
> 
> ```shell
> flatpak run io.github.realmazharhussain.GdmSettings//master
> ```
> 
> Note the `//master` at the end of the command.

Please excuse me. Was not at the PC in the last days.

Yes. Very well, in fact. It's work for me now.
Thank you very much!

**Comment by realmazharhussain** [comment]
> @edwardally @Alvimm @Truemmerer @stefanmaric
>
> Is it working for you too now?
> 
> Here are the links to the new packages again [gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/8767927/gdm-settings.flatpak.zip) [gdm-settings.AppImage.zip](https://github.com/realmazharhussain/gdm-settings/files/8767926/gdm-settings.AppImage.zip)
> 
> **Edit:** If you have previously installed the flatpak from Flathub, you will need to run the following command in order to run this version of the app instead of the one from Flathub.
> 
> ```shell
> flatpak run io.github.realmazharhussain.GdmSettings//master
> ```
> 
> Note the `//master` at the end of the command.

@sorcererinferior and @Nakamerica,
What about you? Is it working for you too or not?

**Comment by realmazharhussain** [comment]
## Status

### Fixed for
@Cherro59
@PimpinPumpkin
@Truemmerer

### Not working for
@stefanmaric

### Unknown status for
@edwardally
@Alvimm
@sorcererinferior
@Nakamerica

**Comment by stefanmaric** [comment]
The last flatpak build shared here is kind of working for me. It does apply the changes and doesn't break GDM, but half of the times when I apply a change it breaks the gnome shell theme for my current session.

![Screenshot from 2022-06-13 11-11-28](https://user-images.githubusercontent.com/1009040/173321156-faf0aa4d-f090-41aa-9b0b-1b596cdd46d1.png)
![Screenshot from 2022-06-13 11-11-06](https://user-images.githubusercontent.com/1009040/173321161-5b337443-3019-4c0a-bf16-5b7b32ee57eb.png)

I'm able to locate the logout/porweroff button and after login/restart it is fixed.

**Comment by realmazharhussain** [comment]
This is how GNOME Shell behaves when the file `/usr/share/gnome-shell/gnome-shell-theme.gresource` is modified. The app cannot prevent that. But at some point in future, the app would display a dialog asking the user to re-login.

**Comment by realmazharhussain** [comment]
Since everyone who reported back have said that the problem has been fixed, I'll be closing the issue in a few days. If anyone is still having the issue, feel free to comment.

**Comment by PimpinPumpkin** [comment]
> Since everyone who reported back have said that the problem has been fixed, I'll be closing the issue in a few days. If anyone is still having the issue, feel free to comment.

Can't wait for the official release on Flathub 🚀. Thank you kindly for your work.

**Comment by edwardally** [comment]
> # Status
> ## Fixed for
> 
> @Cherro59 @PimpinPumpkin @Truemmerer
> ## Not working for
> 
> @stefanmaric
> ## Unknown status for
> 
> @edwardally @Alvimm @sorcererinferior @Nakamerica

Hi, Sorry for being late reply. 

Yes.. Its works for me too. Thank you so much!!!!!!

**Comment by realmazharhussain** [comment]
You are welcome and thank you for submitting the issue and helping me fix it.

**Comment by realmazharhussain** [comment]
Closing the issue now.

**Comment by Radical4ever** [comment]
for me too i forgot to tell 😅
