### ISSUE TITLE
Change image prevented GDM from starting

### ISSUE THREAD

**Issue by rwarnatsch** [realmazharhussain/gdm-settings#3]
I am on arch linux 5.16.5-arch1-1 running gnome 41 (gnome-shell 1:41.3-1) with wayland (1.20.0-1) and installed version 0.2+alpha-1 from AUR gdm-settings. 
I choose a background image for the GDM and applied it.  The app didn't display the image, but tried to.  Due to another issue, I did a reboot, and GDM stopped at "Oh no something has gone wrong".  

What seemed finally to get GDM working again is that I deleted /etc/dconf/db/gdm.d and the gdm profile under /etc/dconf/profile.  GDM did not regenerate these on reinstall.  I had to copy the gdm profile from /usr/share/dconf/profile to etc, manually create the /etc/dconf/db/gdm.d directory, and run dconf update.  

I didn't look at /etc/dconf/db/gdm.d before I deleted it, I can't say what may have gone wrong.  GDM was less than helpful, even in debug mode.

**Comment by realmazharhussain** [comment]
Thank you for reporting the issue.

Did you try changing the background again? If yes, did it break GDM again?

**Comment by rwarnatsch** [comment]
Looks like it takes, in addition to fixing dconf/db/gdm, a possible a removal and reinstall of gdm, but for sure a reinstall of gnome-shell to get gdm to work again.

**Comment by realmazharhussain** [comment]
If you need to reinstall gnome-shell, it means this app causes problems in `/usr/share/gnome-shell/gnome-shell-theme.gresource` file not in `/etc/dconf`.

If you don't mind, I would like you to change GDM background again, then run the command `gresource extract /usr/share/gnome-shell/gnome-shell-theme.gresource /org/gnome/shell/theme/gnome-shell.css | tail -20` and report its output here.

In the end, run the command `cp -f /usr/share/gnome-shell/gnome-shell-theme.gresource.default /usr/share/gnome-shell/gnome-shell-theme.gresource` to prevent GDM from refusing to start. But do note that this command will revert theme and background to the original/default ones.

**Comment by rwarnatsch** [comment]
Here is the tail: $ gresource extract /usr/share/gnome-shell/gnome-shell-theme.gresource /org/gnome/shell/theme/gnome-shell.css | tail -20

.screen-shield-background {
  background: black;
  box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.6); }

#lockDialogGroup {
  background-color: #282828; }

#unlockDialogNotifications StButton#vhandle, #unlockDialogNotifications StButton#hhandle {
  background-color: rgba(53, 53, 53, 0.3); }
  #unlockDialogNotifications StButton#vhandle:hover, #unlockDialogNotifications StButton#vhandle:focus, #unlockDialogNotifications StButton#hhandle:hover, #unlockDialogNotifications StButton#hhandle:focus {
    background-color: rgba(53, 53, 53, 0.5); }
  #unlockDialogNotifications StButton#vhandle:active, #unlockDialogNotifications StButton#hhandle:active {
    background-color: rgba(27, 106, 203, 0.5); }
/* 'GDM Settings' App Provided CSS */
#lockDialogGroup {
  background-image: url('file:///opt/backgrounds/Origin_of_nature_by_Julian_Tomasini.jpg');
  background-size: cover;
}
I will reboot to ensure it works.

**Comment by rwarnatsch** [comment]
So no go on the reboot.  Gdm was still going "oh no" .  I tried various combinations of fixes and the only thing that turned out to be required was a reinstall of gnome-shell (even after the copy over of the default).  The dconf changes are in place and not causing any noticable problem.  GDM didn't have to be touched at all.

**Comment by realmazharhussain** [comment]
Can you change background using tool `set-gdm-theme` from `gdm-tools` AUR package?

Try it and let me know if that also breaks GDM.

The command to change background is `set-gdm-theme set -b [/path/to/image]`

**Comment by rwarnatsch** [comment]
I had tried it before and I'm pretty sure it put the background image file into /usr/share/gnome-shell/theme but this didn't work as in it didn't change the background but didn't effect gdm.  Which is how I came to find your app.  I uninstalled gdm-tools as part of my gdm purge, and there seems to be a new version.  Now it seems to put a file into the same directory called gdm-background, at least that file has the change time of when I ran set-gdm-theme.   However, it still does not change the background.  
set-gdm-theme did not make any changes to dconf, which I think are now required to make the background change work.
One weird thing, /etc/dconf/db/gdm.d/ is now empty, but I didn't do that.  But there were updates to both gdm and gnome-shell since the last time I looked.

**Comment by realmazharhussain** [comment]
I have updated `gdm-tools-git` package. Now, try if it works.

**Comment by rwarnatsch** [comment]
Yes!  That works.  The image is streched over three monitors, which is okay.   But a scaled option would be nice.

**Comment by realmazharhussain** [comment]
Does running ``gnomeconf2gdm`` command from `gdm-tools-git` also break GDM or is it just this app that breaks GDM?

**Comment by rwarnatsch** [comment]
Nope, it doesn't break GDM.  However, there is no noticable change.  I'm assuming I would have the different cursor at least?  No change in the background from what I set gdm-tools, which is not the same as my gnome background.

**Comment by realmazharhussain** [comment]
I think this issue might be fixed now. You can install the latest `gdm-settings-git` package and check if it works.

**Comment by rwarnatsch** [comment]
Didn't work again.  Just needed the reinstall of gnome-shell to fix.  I was initially only interested in getting the background changed (which it still is from gdm-tools, even after the gdm-settings and reinstall).  So that's all I really looked at on gdm-settings.  Now that I'm more familiar, I see it has all my gnome customizations on it.  So when I hit apply after changing the image, are those applied too?  Because I'm not sure all the customizations have been moved to /use/share/.... But there should be earlier versions there already.  It might be a problem.  I will have to go through evernthing and update them, just to be sure it isn't references to things that are only in .local of my main account.

**Comment by realmazharhussain** [comment]
Yes, it applies everything. But it only modifies following three files

```
/etc/dconf/profiles/gdm
/etc/dconf/db/gdm.d/95-gdm-settings
/usr/share/gnome-shell/gnome-shell-theme.gresource
```

Additionally, it does add 'default-pure' shell theme in `/usr/share/themes` but that shouldn't be a problem.

**Comment by realmazharhussain** [comment]
I installed Arch Linux and tested this application. I works fine for me.

Do you use a custom package of GDM like `gdm-plymouth`, `gdm-prime` or `gdm-git`?

**Comment by realmazharhussain** [comment]
#29 is probably the same issue as this one.
