### ISSUE TITLE
Run without force to use adwaita [FEATURE] 

### ISSUE THREAD

**Issue by docop** [realmazharhussain/gdm-settings#36]
### Description

Hi  You app look pretty good for a quick setting adjustment and perfect as appimage format. Also, i would like to know if it be possible to have it run in an auto-detect mode for the font, rather than having the adwaita needed and cannot run if it's not present ?  Like, if we use the dark version.. it cannot run and just a quick test over Mate , having Ambiant-Mate-Dark cause also the line 7 fail..

 And is there an option to set on the On screen keyboard ?

Thanks

**Comment by realmazharhussain** [comment]
## Adwaita
Adwaita is not just a theme anymore. LibAdwaita contains a ton of useful widgets a lot of which are used by this application. This application cannot just ditch LibAdwaita now.

## Font
You can change the interface font using GNOME Tweaks app and it should apply to this application too. If not, there is something wrong with your setup.

## Theming
LibAdwaita apps are not supposed to be themed but they allow changing accent and other colors.

## Dark Theme
LibAdwaita apps also have a dark mode. I you are on GNOME 41 or earlier, use "Color Scheme Simulator" to turn dark mode on.

## Theme causing Error
If you set the theme using GNOME Tweaks, it shouldn't cause any errors.
**Note:** Copying the contents of a theme into `~/.config/gtk-4.0/` is not a good idea and may cause this and other GTK4 apps to crash or misbehave.

## OnScreen Keyboard
Login Screen should have an accessiblilty button/menu on the top bar which also contains the option of OnScreen Keyboard. This feature is built-in and this application doesn't need to include it.

**Comment by docop** [comment]
Oh, so the app is only focus on gnome desktop then ?

**Comment by realmazharhussain** [comment]
Kinda. Who would use GDM other than GNOME users?
