### ISSUE TITLE
Settings have no effect on Ubuntu (flatpak)

### ISSUE THREAD

**Issue by hilemec** [realmazharhussain/gdm-settings#41]
### What happened?

All setting changed don't made differences

### Expected behavior

I suppose that a set change effectively make a DM change but it doesn't happen

### To Reproduce

opening program and make changes

### Detailed Explaination (Optional)

all kind of change

### Application Version

gdm-settings v0.5.2

### Source

flatpak

### Environment

Ubuntu 22.04
GNOME Shell 42.0

**Comment by realmazharhussain** [comment]
Did you apply the settings?

**Comment by hilemec** [comment]
Yes I did , clicking on the top right button

Il mar 3 mag 2022, 10:35 Mazhar Hussain ***@***.***> ha
scritto:

**Comment by realmazharhussain** [comment]
I don't know why other settings are not getting applied to GDM but shell theme and top bar tweaks were not supported on Ubuntu (before). Now, I have added support for Ubuntu.

But it will take time for flatpak to get an update. When version v0.5.3 comes out, it should support Ubuntu.

Alternatively, you can compile and install the latest development version of the app by following [these instructions](https://github.com/realmazharhussain/gdm-settings#method-2).

**Comment by realmazharhussain** [comment]
Fixed it. Should work fine now.
