### ISSUE TITLE
[FEATURE] Per monitor background image

### ISSUE THREAD

**Issue by McCarthee** [realmazharhussain/gdm-settings#44]
### Description

On a multi-monitor setup, the background image stretches across every monitor. Would it be possible to add the ability to pick a background for each monitor separately? That way I can make my login screen look more consistent with my desktop.

Thank you for making this app by the way, been looking for something exactly like this for a while. 👍

**Comment by realmazharhussain** [comment]
This application provides a Graphical Interface for settings that can already be changed.

I don't think GDM supports changing background of a multi-monitor setup.

So, currently, it is not possible. If it ever seems possible, I'll try adding this setting.
