### ISSUE TITLE
[BUG] Significant amount of folders, as well as all files are missing in the file picker

### ISSUE THREAD

**Issue by TPO100Cofficial** [realmazharhussain/gdm-settings#45]
### What happened?

okay! i wanted to use this app to customize my new gdm3 installation, switching over from lightdm
unfortunately, when i try to pick an image to change the background look, relevant folders (/home/username/*) aren't displayed in the file picker. in fact, a lot of folders are missing, seemingly at random?
it gets worse by running the app with sudo, _somehow:_ the entire /home folder is empty
i attempted to circumvent this by creating a folder in /usr/share. however, like many other folders, it is not displayed, _for **some** reason_
![image](https://user-images.githubusercontent.com/33667869/167044115-188a7336-d8ba-49a7-9a56-aefbaf84fae8.png)

### Expected behavior

the app should allow me to select files from folders

### To Reproduce

i have. absolutely no idea.
i'm on linux mint 20.3 cinnamon, which doesn't have this app on it's software store, hence i had to import the flatpak repo
when i: open the app, set background type to "image" in the appearance tab, and click "choose file", it sends me to a blank screen with only the sidebar to navigate. this also happens with miscellaneous > logo > choose file

### Application Version

0.5.2

### Source

Flatpak

### Environment

- **OS**:  Linux Mint 20.3 Cinnamon
- **GNOME**:  No

**Comment by realmazharhussain** [comment]
Is `xdg-desktop-portal-gtk` installed on your system? Flatpak apps need that package to **properly** access files on the host system.
