### ISSUE TITLE
GDM crash after changing background.

### ISSUE THREAD

**Issue by arun54321** [realmazharhussain/gdm-settings#53]
### What happened?

Change background

### Expected behavior

GDM crash

### To Reproduce

unmodified gdm settings - initial state
change background - image -select jpg image - apply

### Application Version

0.5.3 

### Source

flatpak

### Environment

- **OS**: fedora 36
- **GNOME**: 42

**Comment by realmazharhussain** [comment]
Plz! See issue #29.

**Comment by arun54321** [comment]
Since it is already reported, I am closing this.
