### ISSUE TITLE
App crashes when trying to run

### ISSUE THREAD

**Issue by Bimi124** [realmazharhussain/gdm-settings#54]
### What happened?

The app doesn't run at all.

### Expected behavior

The app runs and I can switch the login managers theme

### To Reproduce

Install the 0.5.3 release via flatpack or download the AppImage and try to run it

### Detailed Explaination (Optional)

When running the app using `flatpak run io.github.realmazharhussain.GdmSettings` or `./Login_Manager_Settings-nodeps.AppImage`, the following error message appears:
```
Traceback (most recent call last):
  File "/app/bin/gdm-settings", line 13, in <module>
    from gdm_settings import gdm_settings_gui
  File "/app/lib/python3.9/site-packages/gdm_settings/gdm_settings_gui.py", line 15, in <module>
    from . import settings_manager
  File "/app/lib/python3.9/site-packages/gdm_settings/settings_manager.py", line 151, in <module>
    class GResourceUtils:
  File "/app/lib/python3.9/site-packages/gdm_settings/settings_manager.py", line 163, in GResourceUtils
    GdmGresourceAutoBackup = f'{GdmGresourceFile}.default'
NameError: name 'GdmGresourceFile' is not defined
```

### Application Version

v0.5.3

### Source

Flatpack AND AppImage

### Environment

- **OS**: Ubuntu 20.04.4 LTS (64 bit)
- **GNOME**:  3.36.8

**Comment by realmazharhussain** [comment]
Are you using the main Ubuntu or a flavor of Ubuntu? In other words, is GDM installed on your system?

**Comment by Bimi124** [comment]
I use the main Ubuntu release. It looks like GDM is installed (Ther's a settings entry called "GNOME-Version", I have apps like gnome-terminal installed and I am using gnome-tweaks to apply themes).

**Comment by realmazharhussain** [comment]
Does the file `/usr/share/gnome-shell/gnome-shell-theme.gresource` exist?

**Comment by Bimi124** [comment]
It does.

**Comment by realmazharhussain** [comment]
I have changed some things in the app.

Here are new packages;
- [AppImage](https://github.com/realmazharhussain/gdm-settings/files/8747457/gdm-settings.AppImage.zip)
- [Flatpak](https://github.com/realmazharhussain/gdm-settings/files/8747458/gdm-settings.flatpak.zip)
.

**Comment by Bimi124** [comment]
Still not working :(
```
Traceback (most recent call last):
  File "/tmp/.mount_gdm-setYXm6Z/usr/bin/gdm-settings", line 13, in <module>
    from gdm_settings import gdm_settings_gui
  File "/tmp/.mount_gdm-setYXm6Z/usr/lib/python3.10/site-packages/gdm_settings/gdm_settings_gui.py", line 8, in <module>
    gi.require_version("Adw", '1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Adw not available
```
Btw I can't install the flatpack because it's "unsupported".

**Comment by realmazharhussain** [comment]
> Still not working :(

Sorry! I forgot the AppImage does not run on Ubuntu 20.04. See issue #9 for more details.

> Btw I can't install the flatpack because it's "unsupported".

What do you mean "unsupported"?

**Comment by Bimi124** [comment]
It says so when I'm trying to install the flatpack via double-clicking

**Comment by realmazharhussain** [comment]
Do not double click.

- Right click the flatpak.
- Click on "Open with".
- Select "Software Install".

  If "Software Install" is not in the options, click on "More Applications" and find "Software Install" and click on it.

**Comment by realmazharhussain** [comment]
If above method does not work,

- Right click on the empty space in the folder which contains the flatpak
- Select "Open in terminal"
- Run the command

  ```bash
  flatpak install gdm-settings.flatpak
  ```

**Comment by realmazharhussain** [comment]
In any case, do not forget to unzip(extract) the .zip file before proceeding.

**Comment by Bimi124** [comment]
It works now.

**Comment by realmazharhussain** [comment]
Thank you for reporting the issue and helping me fix it.

Closing it now. If required, you can re-open it.
