### ISSUE TITLE
Use a localization platform

### ISSUE THREAD

**Issue by yarons** [realmazharhussain/gdm-settings#57]
### Description

Using a localization platform will allow easier localization collaboration and will increase the number of translations available.

I personally prefer Weblate because it's open source and offers Libre hosting plans for open source projects but there are many other options (Most of them closed source).

BTW it also means that there should always be an updated POT file as part of the current code.

Thanks.

**Comment by realmazharhussain** [comment]
We (the translators) had a [discussion](https://github.com/realmazharhussain/gdm-settings/discussions/23) about this and we decided that the best option was to use the discussion notifications to tell the translators when there is new/modified text for them to translate.

I know it is not the most discoverable thing but I have [mentioned](https://github.com/realmazharhussain/gdm-settings/wiki/Translations#get-notified-when-translations-need-updates) the [discussion](https://github.com/realmazharhussain/gdm-settings/discussions/23) at the end in the [Translation Manual](https://github.com/realmazharhussain/gdm-settings/wiki/Translations).

If you really want for the project to be on something like Weblate, you can suggest it in the [discussion](https://github.com/realmazharhussain/gdm-settings/discussions/23) and the decision will be made unanimously.

**Comment by realmazharhussain** [comment]
The app uses [Weblate](https://hosted.weblate.org/engage/gdm-settings) now.
