### ISSUE TITLE
Wallpaper Adjustment

### ISSUE THREAD

**Issue by oparada1988** [realmazharhussain/gdm-settings#59]
### Description

option to adjust wallpaper: scale, centered, spanned, etc

### Explaination

When applying a new wallpaper it is blown up and cannot see it in its entirety

**Comment by nlogozzo** [comment]
Especially for dual-monitor setup, the wallpaper spans across the two screens.
But I would like the option to have the wallpaper show separately on each screen similar to how the gnome desktop does it:
![image](https://user-images.githubusercontent.com/17648453/171569483-b5963da3-a3f6-4a7d-b884-ad2b9439b782.png)

**Comment by realmazharhussain** [comment]
> option to adjust wallpaper: scale, centered, spanned, etc

I will add that to planned features list

**Comment by realmazharhussain** [comment]
> Especially for dual-monitor setup, the wallpaper spans across the two screens.
> But I would like the option to have the wallpaper show separately on each screen similar to how the gnome desktop does

Unfortunately, GDM does not differentiate among different monitors properly. So, there is no way to achieve that except by modifying the chosen image which is a hard task to do correctly. So, for now, I do not plan on implementing this feature.
