### ISSUE TITLE
Window Scaling Issue

### ISSUE THREAD

**Issue by nlogozzo** [realmazharhussain/gdm-settings#60]
The window does not scale properly when maximized or resized past a certain point:

![image](https://user-images.githubusercontent.com/17648453/171570086-91792a2d-c2b3-4123-b4cb-c430120a6d39.png)
![image](https://user-images.githubusercontent.com/17648453/171570134-e26f24c8-a034-4982-aa1e-a6dca2edb533.png)

**Comment by realmazharhussain** [comment]
## 1
I could not reproduce the in-app notification (a.k.a Toast) being nearly in the middle of the window.

## 2
> The window does not scale properly when maximized or resized past a certain point

This is how AdwClamp works. So, all LibAdwaita settings apps behave this way. For example

![image](https://user-images.githubusercontent.com/67191572/172775127-6a79e768-0f20-4025-a057-236219c7b4df.png "GNOME Settings")

![image](https://user-images.githubusercontent.com/67191572/172775560-e5daf941-912c-472e-8666-86a17d809d87.png "Extensions")

![image](https://user-images.githubusercontent.com/67191572/172775717-0be0294e-cfc1-49b7-bb2c-2f42512d1c37.png "Extension Manager")

## Solved (kinda)
I have kind of fixed the issue but it still won't look good on a 4k or 8k display if scaling is not enabled. This is how it looks maximized on a 1366x768 display (no scaling) now

![image](https://user-images.githubusercontent.com/67191572/172776683-6b8f299e-c8bb-49d6-83b5-bb74dce27b58.png "Login Manager Settings")

The next release will include this fix.
