### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [realmazharhussain/gdm-settings#61]
### What happened?

https://hosted.weblate.org/projects/gdm-settings/language-names/#information is NC, meaning non-commercial. Non-libre licenses are incompatible with the AGPLv3+ license of the project.
It can be changed in
https://hosted.weblate.org/settings/gdm-settings/language-names
https://hosted.weblate.org/settings/gdm-settings/glossary

### Expected behavior

AGPLv3+ for the translations

### To Reproduce

Go to https://hosted.weblate.org/projects/gdm-settings/language-names/#information and see it listed as 

### Detailed Explaination (Optional)

Creative Commons Attribution Non Commercial Share Alike 4.0 International is not compatible with AGPLv3+

### Application Version

Latest

### Source

Source Code

### Environment

- **OS**: Not applicable
- **GNOME**: Not applicable

**Comment by realmazharhussain** [comment]
Fixed
