### ISSUE TITLE
Can not change cursor theme

### ISSUE THREAD

**Issue by vikashraghavan** [realmazharhussain/gdm-settings#62]
### What happened?

The cursor theme can not be changed since the drop down option is not available.
![image](https://user-images.githubusercontent.com/48412820/174586288-4ebbb4b8-2480-4f6e-841f-227bbc2fe5bb.png)

But i have cursor theme in place for gnome. Do I need it to move somewhere or is there any fix?
![image](https://user-images.githubusercontent.com/48412820/174586531-728a7223-4fec-481b-b870-1defc8525506.png)

### Expected behavior

Expected to show available cursor theme and change them

### To Reproduce

NA

### Application Version

0.5.2

### Source

AUR

### Environment

- **OS**:  Arch Linux
- **GNOME**:  42.2

**Comment by realmazharhussain** [comment]
> Do I need it to move somewhere?

Yes, you need to move it to either `/usr/share/icons/` or `/usr/local/share/icons/`.

**Comment by realmazharhussain** [comment]
GDM does not have access to your home directory. That is why the themes have to be in a system-wide location for them to be available to GDM.
