### ISSUE TITLE
Entire Gnome freezes on applying the changes from the app.

### ISSUE THREAD

**Issue by austinrojers** [realmazharhussain/gdm-settings#64]
### What happened?

Entire Gnome freezes on applying the changes from the app.
Just as I enter the password for root permissions to apply the changes, the system freezes.
Then I would have to switch to 'tty' and reboot.
The GDM changes are applied though and the changes are visible after the reboot.

### Expected behavior

Gnome is not supposed to freeze on changing GDM settings

### To Reproduce

Change some settings from the app and press apply, and the system freezes.

### Application Version

 Branch: stable  Version: 0.6

### Source

flatpak

### Environment

- **OS**: Fedora Linux 36
- **GNOME**: GNOME 42.2

**Comment by austinrojers** [comment]
file:///home/austin/error_log.txt
file:///home/austin/full_log.txt

**Comment by realmazharhussain** [comment]
@austinrojers 
Hey man. You do not need to paste file's contents here. Just drag files from file manager into the text field and they will be uploaded and become links.

I request that you to delete the contents replace it with actual files.

Thanks.

**Comment by austinrojers** [comment]
is it visible to you now?

**Comment by austinrojers** [comment]
https://pastebin.com/7Dfc1zMx

**Comment by realmazharhussain** [comment]
Thank you.

**Comment by austinrojers** [comment]
I am not able to paste:
error_log.txt, it is larger than the limit

**Comment by realmazharhussain** [comment]
You can compress it and then post it here.

**Comment by austinrojers** [comment]
Not able to upload it on Github, sorry for the delay.
I am a little busy now.

**Comment by austinrojers** [comment]
**full_log:**

https://pastebin.com/YWBBZ0Fc

**Comment by realmazharhussain** [comment]
> Sorry for the delay.
> I am a little busy now.

No worries.

And now, I am sorry for being so late. I use a mobile package for internet that ends at 6:00 PM PKT. That is why, I couldn't use use the internet to reply.

**Comment by realmazharhussain** [comment]
Thank you for sharing the files with me but you don't need to add them to pastebin either.

Here is a video showing how to upload files directly to GitHub

https://user-images.githubusercontent.com/67191572/175454038-3bc49d99-19e8-46ee-acff-30a88d8c83bf.mov

**Comment by austinrojers** [comment]
Thanks
That was so silly of me, not able to find that, I was trying to drag and drop the files which didn't work.

[full_log.txt](https://github.com/realmazharhussain/gdm-settings/files/8972962/full_log.txt)
[error_log.txt](https://github.com/realmazharhussain/gdm-settings/files/8972963/error_log.txt)

**Comment by realmazharhussain** [comment]
Do you use XOrg? If yes, try applying the settings in a Wayland session and see if the issue also occurs on Wayland.

**Comment by austinrojers** [comment]
Ya in Wayland, the screen freezes for maybe 4-5 seconds and it revives back to normal with a flicker.
So, ya you can say there is no issue.
In Xorg, it freezes forever and I would have to reboot.

**Comment by realmazharhussain** [comment]
Can you run following commands before applying,

```bash
journalctl -b -p3 > ~/error_log_before.txt
journalctl -b > ~/full_log_before.txt
```

following commands after applying (after you switch to TTY, before rebooting),

```bash
journalctl -b -p3 > ~/error_log_after.txt
journalctl -b > ~/full_log_after.txt
```

and then post all 4 files (`error_log_before.txt`, `error_log_after.txt`, `full_log_before.txt`, and `full_log_after.txt`) here?

This will help me in finding out exactly what went wrong.

**Comment by austinrojers** [comment]
Interesting!
Today I tried changing some setting and applying it in Xorg, it behaved the same as in Wayland, froze for a few seconds and revived back; the changes are also reflected in the login screen. I think it wasn't the issue of GDM settings, maybe some system updates yesterday fixed the issue.

**Comment by realmazharhussain** [comment]
TouchEgg seemed to be the thing causing this but I had to make sure. But, now that this issue does not occur anymore there is no reason to debug it.

I'm closing this issue. If ever needed, feel free to re-open it.

**Comment by austinrojers** [comment]
Thank you for your support.

**Comment by realmazharhussain** [comment]
You are welcome and thank you for taking the time to report the issue and help me diagnose it.
