### ISSUE TITLE
Icon by GNOME HIG

### ISSUE THREAD

**Issue by gargullia** [realmazharhussain/gdm-settings#66]
### Description

What are your ideas?

**Comment by realmazharhussain** [comment]
What do you mean? Do you want me to redo the icon and follow HIG this time or are offering to design an icon that follows HIG?

> What are your ideas?

An app icon that follows HIG seems good. Other than that, I have no ideas.

**Comment by gargullia** [comment]
@realmazharhussain I would try to draw, but I have no ideas

**Comment by realmazharhussain** [comment]
OK. Then I'll check with HIG sometime (IDK when).

**Comment by thalesruan** [comment]
Hi, I had an icon idea, hope you like it.

![io github realmazharhussein GdmSettings-template](https://user-images.githubusercontent.com/7895807/175849820-864a9239-060b-49f2-b679-c97e9be339f1.svg)

![Visualizar](https://user-images.githubusercontent.com/7895807/175849926-71162827-10af-4727-8718-b957fbadcd48.png)

**Comment by thalesruan** [comment]
Hi, I had an icon idea, hope you like it.

![io github realmazharhussein GdmSettings-template](https://user-images.githubusercontent.com/7895807/175850172-01c9a9ec-4f62-4a52-80d7-8fb5939002b9.svg)
![Visualizar](https://user-images.githubusercontent.com/7895807/175850168-2f0d964a-10d2-4164-a391-05a4d5465843.png)

**Comment by realmazharhussain** [comment]
Amazing. Good work. Definitely gonna use this one.

Although, I think the input field and the background should have a little more contrast.

Thank you very much.

In designer credits in the about dialog of the app, we need to have your name. Please! Provide your full name and email (if you are comfortable) so that I can add it to the about page.

**Comment by realmazharhussain** [comment]
Cannot open the svg in 'App Icon Preview' app. Can you post a zipped version of it?

**Comment by thalesruan** [comment]
Of course, just waiting for your approval. I could make a pull request too, if you prefer.

**Comment by realmazharhussain** [comment]
> Of course, I was just waiting for your approval.

The icon seems excellent now.

> I could make a pull request too, if you prefer.

Yes. A pull request is preferred.

## Instructions for Pull Request
- Delete the `data/icon-sources` directory
- Put the source svg as `data/icons/io.github.realmazharhussain.GdmSettings.Source.svg`
- Put the exported regular and symbolic svg's in their respective subdirectories in `data/icons`

  That is

  - Regular: `data/icons/scalable/apps/io.github.realmazharhussain.GdmSettings.svg`
  - Symbolic: `data/icons/symbolic/apps/io.github.realmazharhussain.GdmSettings-symbolic.svg`

**Comment by thalesruan** [comment]
Pull request done!

**Comment by realmazharhussain** [comment]
PR #72 merged.

**Comment by realmazharhussain** [comment]
Still cannot open the source svg even the one provided in pull request.

**Comment by realmazharhussain** [comment]
Please make sure to upload the svg that has its layers intact and upload a zipped file because if you don't zip it before uploading, GitHub will strip the svg layers.

**Comment by thalesruan** [comment]
Done. I uploaded compressed SVG files and a devel scalable icon.

**Comment by realmazharhussain** [comment]
By svg, I didn't mean the exported svg. What I asked for is the file that you open in 'App Icon Preview' app to preview and generate other files.

**Comment by realmazharhussain** [comment]
Hey, @thalesruan. You there?

**Comment by thalesruan** [comment]
@realmazharhussain Sorry friend, I have a very busy week, and I almost forgot about the icon. Sorry again.

Where coud I upload the original SVG for you? Here? Or I have to do another pull request?

**Comment by realmazharhussain** [comment]
> Where coud I upload the original SVG for you? Here? Or I have to do another pull request?

As you like.

**Comment by realmazharhussain** [comment]
If you do create a PR, remember to run the following command before making any commits of your own.

```bash
git pull https://github.com/realmazharhussain/gdm-settings.git main
```

**Comment by thalesruan** [comment]
Hey @realmazharhussain I preferred to send the zipped file right here. Hope this is what you need.
[source.zip](https://github.com/realmazharhussain/gdm-settings/files/9067613/source.zip)

**Comment by realmazharhussain** [comment]
Nah, man. I do not need **these** files. I need the file that you open in '**App Icon Preview**' app and I cannot open any of these files in '**App Icon Preview**' app. Please! make sure that you can open the file in '**App Icon Preview**' app before sending it to me.

**Comment by thalesruan** [comment]
Well, man, sorry. Im not understanding you. You can open one of the files I sent you in 'App Icon Preview', and all of files has its original layers. Im sendind here a video where I open the file in 'App Icon Preview'.
[Gravação de tela de 08-07-2022 21:16:39.webm](https://user-images.githubusercontent.com/7895807/178084234-bd923e5f-d47b-4d24-94b6-1d85ce8dd029.webm)

**Comment by realmazharhussain** [comment]
The screencast you uploaded is corrupted. Screencasting does not work properly on GNOME 42.2 as you can see in [this issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5609) I created on GNOME Shell GitLab.

**Comment by realmazharhussain** [comment]
https://user-images.githubusercontent.com/67191572/178089078-bc7d17e9-fcaa-4c60-908d-19b7d786c7bb.mp4

As you can see in this video, I cannot open the source file you provided in 'App Icon Preview' but I can open `org.gnome.design.BannerViewer.Source.svg`.

I think I know what is going on here. You optimize/compress the source before uploading. That is why I cannot open it in 'App Icon Preview'. What I've been asking for this whole time is the actual unmodified source svg which which is definitely much more than just 30kB in size. It will be more like 200kB or 300kB in size or may be even bigger.

**Comment by thalesruan** [comment]
Oh, now I got it! Sorry man, I think now I sent you the right file, I made sure that it opens correctly in 'App Icon Preview" now. you wanted something so simple and i just complicated things 😅

[source.zip](https://github.com/realmazharhussain/gdm-settings/files/9075793/source.zip)

**Comment by realmazharhussain** [comment]
> Oh, now I got it! Sorry man, I think now I sent you the right file, I made sure that it opens correctly in 'App Icon Preview" now. you wanted something so simple and i just complicated things sweat_smile
> 
> [source.zip](https://github.com/realmazharhussain/gdm-settings/files/9075793/source.zip)

This is the same file as this one.

> Hey @realmazharhussain I preferred to send the zipped file right here. Hope this is what you need. [source.zip](https://github.com/realmazharhussain/gdm-settings/files/9067613/source.zip)

**Comment by thalesruan** [comment]
I noticed it minutes after I sent it. Now Im sending the correct file.
[io.github.realmazharhussain.GdmSettings.Source.zip](https://github.com/realmazharhussain/gdm-settings/files/9075815/io.github.realmazharhussain.GdmSettings.Source.zip)

**Comment by realmazharhussain** [comment]
Thank you very much. This is exactly what I asked for.

**Comment by thalesruan** [comment]
Finally we managed to understand each other! haha
You prefer I make a new PR with the correct file?

**Comment by realmazharhussain** [comment]
As you like

**Comment by thalesruan** [comment]
Okay, I upload the correct source file, then I opened it on 'App Icon Preview', exported the icons correctly and upload it too. I gonna open the PR now. Thank you for your patience.

**Comment by realmazharhussain** [comment]
OK

**Comment by realmazharhussain** [comment]
PR merged. Closing the issue now.
