### ISSUE TITLE
always error

### ISSUE THREAD

**Issue by olaulau** [realmazharhussain/gdm-settings#79]
### What happened?

just launched, click apply, and this error message :
"Didn't apply. Chosen background image could not be found. Please! choose again."

### Expected behavior

no error when no change
not this error when background type != image

### To Reproduce

download
launch
click apply

### Application Version

v0.6

### Source

appimage

### Environment

- **OS**: debian testing
- **GNOME**: 42.2

**Comment by iscandarster** [comment]
I have the same error. Just downloaded the .Appimage today from your github. 
Only launching it and hitting the Apply button it throws the same error. 
Ubuntu 22.04  
![image](https://user-images.githubusercontent.com/76690375/180637687-07bf114c-79eb-4def-bec2-1b1f779201b3.png)

**Comment by realmazharhussain** [comment]
> I have the same error. Just downloaded the .Appimage today from your github. Only launching it and hitting the Apply button it throws the same error. Ubuntu 22.04 ![image](https://user-images.githubusercontent.com/76690375/180637687-07bf114c-79eb-4def-bec2-1b1f779201b3.png)

Even when background type is set to none?

**Comment by iscandarster** [comment]
> > I have the same error. Just downloaded the .Appimage today from your github. Only launching it and hitting the Apply button it throws the same error. Ubuntu 22.04 ![image](https://user-images.githubusercontent.com/76690375/180637687-07bf114c-79eb-4def-bec2-1b1f779201b3.png)
> 
> Even when background type is set to none?

Thanks for answering.

Yes. By default background type is set to None and I don't change it. 
Actually I launch the .Appimage, and right then just click on the Apply button. 
I do nothing else than launching and clicking. And then the error message shows up

**Comment by realmazharhussain** [comment]
Try this AppImage.

[gdm-settings.AppImage.zip](https://github.com/realmazharhussain/gdm-settings/files/9216244/gdm-settings.AppImage.zip)

**Comment by iscandarster** [comment]
> Try this AppImage.
> 
> [gdm-settings.AppImage.zip](https://github.com/realmazharhussain/gdm-settings/files/9216244/gdm-settings.AppImage.zip)

Below is the result with the provided new .AppImage : 

$ ./gdm-settings.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_gdm-seo0n4OG/usr/lib/python3.10/site-packages/gdm_settings/app.py", line 72, in on_activate
    self.initialize_settings()
  File "/tmp/.mount_gdm-seo0n4OG/usr/lib/python3.10/site-packages/gdm_settings/app.py", line 349, in initialize_settings
    from .settings import Settings
  File "/tmp/.mount_gdm-seo0n4OG/usr/lib/python3.10/site-packages/gdm_settings/settings.py", line 7, in <module>
    from . import gr_utils
  File "/tmp/.mount_gdm-seo0n4OG/usr/lib/python3.10/site-packages/gdm_settings/gr_utils.py", line 24, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
Traceback (most recent call last):
  File "/tmp/.mount_gdm-seo0n4OG/usr/lib/python3.10/site-packages/gdm_settings/app.py", line 118, in on_shutdown
    self.save_window_state()
  File "/tmp/.mount_gdm-seo0n4OG/usr/lib/python3.10/site-packages/gdm_settings/app.py", line 693, in save_window_state
    width, height = widgets.main_window.get_default_size()
AttributeError: 'types.SimpleNamespace' object has no attribute 'main_window'
$

**Comment by realmazharhussain** [comment]
Try this one now.

[gdm-settings.AppImage.zip](https://github.com/realmazharhussain/gdm-settings/files/9219654/gdm-settings.AppImage.zip)

**Comment by iscandarster** [comment]
> Try this one now.
> 
> [gdm-settings.AppImage.zip](https://github.com/realmazharhussain/gdm-settings/files/9219654/gdm-settings.AppImage.zip)

Now I have the following error :: 

![image](https://user-images.githubusercontent.com/76690375/181757033-e3c09cfc-514a-4f10-9088-cfcfe2777677.png)

And then when I kill it from terminal I get :: (don't know if it helps you)

-----
$ ./gdm-settings.AppImage 
^CTraceback (most recent call last):
  File "/tmp/.mount_gdm-se0AHmtC/usr/bin/gdm-settings", line 24, in <module>
    return_value = app.run(sys.argv)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gio.py", line 40, in run
    with register_sigint_fallback(self.quit):
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt

$ 
-----

So I checked what GNOME Display Manager was installed :

-----
$ sudo apt list -a gdm3 
Listing... Done
gdm3/jammy-updates,now 42.0-1ubuntu7 amd64 [installed]
gdm3/jammy 42.0-1ubuntu6 amd64

$ 
-----

**Comment by realmazharhussain** [comment]
What is the output of the following command on your system?

```
ls -1 /bin/*gdm*
```

**Comment by iscandarster** [comment]
> What is the output of the following command on your system?
> 
> ```
> ls -1 /bin/*gdm*
> ```

$ ls -1 /bin/*gdm*
/bin/gdmflexiserver
/bin/gdm-screenshot
$

**Comment by realmazharhussain** [comment]
I meant with the asterisks. That is

```
ls -1 /bin/*gdm*
```

and not

```
ls -1 /bin/gdm
```

**Comment by iscandarster** [comment]
$ ls -1 /bin/*gdm*
/bin/gdmflexiserver
/bin/gdm-screenshot
$

**Comment by realmazharhussain** [comment]
> It's git-hub who removes the stars when I save the message !

Got it.

What is the output of

```bash
which gdm3
```

**Comment by iscandarster** [comment]
$ which gdm3
/usr/sbin/gdm3
$

**Comment by realmazharhussain** [comment]
OK. So, what does

```bash
ls -1 /sbin/*gdm*
```

give?

**Comment by iscandarster** [comment]
$ ls -1 /sbin/\*gdm\*
/sbin/gdm3
$

**Comment by realmazharhussain** [comment]
This AppImage should work now.

[gdm-settings.AppImage.zip](https://github.com/realmazharhussain/gdm-settings/files/9220048/gdm-settings.AppImage.zip)

**Comment by iscandarster** [comment]
No more errors. 
Also it doesn't seem to kake modifications into account.
In Miscellaneous I tried :
Disable User List ON
Enable Logo OFF
Welcome Message ON with "TEST MESSAGE" 

And none of these works after reboot !

Any other settings I should try ?

**Comment by iscandarster** [comment]
Also neither Background Color or Image (.jpeg) works

**Comment by realmazharhussain** [comment]
> No more errors.

That's good.

> Also it doesn't seem to take modifications into account. In Miscellaneous I tried : Disable User List ON Enable Logo OFF Welcome Message ON with "TEST MESSAGE"
> 
> And none of these works after reboot and hitting Apply button !

That seems like a separate issue. Would you mind creating a new issue for this?

> Any other settings I should try ?

Not that I know of.

**Comment by realmazharhussain** [comment]
Thank you very much for reporting the issue and helping me fix it.

Since this problem is fixed, I'm closing the issue.
