### ISSUE TITLE
Add multi monitor support 

### ISSUE THREAD

**Issue by linusrg1** [realmazharhussain/gdm-settings#80]
### Description

Right now the default image just gets spanned across both of your monitors. It would be great if instead the tool was able to at least display your image of choice on each display correctly. Or even better, allow you to choose a different image for each display.

**Comment by realmazharhussain** [comment]
GDM does not allow background images. The current way to change background is a hack and multiple background images cannot be set.

This feature cannot be added to this app unless it is implemented in GDM itself.
