### ISSUE TITLE
Add option to change colour of font on lockscreen

### ISSUE THREAD

**Issue by linusrg1** [realmazharhussain/gdm-settings#81]
### Description

Right now the font still remains whit no matter what. And this can be an issue if you have chosen a brighter wallpaper as it can make the text harder to see.

**Comment by linusrg1** [comment]
Please close this one. I apologize I missed an option.

**Comment by realmazharhussain** [comment]
> Please close this one.

OK. FYI, there was no problem if you closed it yourself.

> I apologize I missed an option.

No worries.
