### ISSUE TITLE
Log in and log out both take longer after using gdm-settings

### ISSUE THREAD

**Issue by caioolivv** [realmazharhussain/gdm-settings#85]
### What happened?

Logging out leads to a grey screen for a couple seconds before showing GDM. Logging in hangs on the background screen before showing the desktop. This happened after using gdm-settings and resetting settings doesn't solve it.

### Expected behavior

Logging in and out should be faster.

### To Reproduce

Happens every time when logging in or out after using gdm-settings.

### Application Version

0.6

### Source

Source Code

### Environment

- **OS**: Fedora 36
- **GNOME**: 42.3

**Comment by caioolivv** [comment]
Uninstalling gdm-settings and reinstalling gdm won't help either.

**Comment by realmazharhussain** [comment]
Hi, I'm sorry for being so late. I'm just a lazy person and logs are too long and detailed for me to focus. But I finally read `error_log.txt`. I didn't expect it to be so small.

Anyway, if you are still using the app and having this issue, I will need some additional log files. `error_log.txt` is too small and does not seem to have enough information while on the other hand, `full_log.txt` is too large for me to find anything useful there.

The logs I would like to receive are following;

```bash
journalctl -b -p3 > error_log.txt
journalctl -b -p4 > warning_log.txt
journalctl -b -p5 > notice_log.txt
```
