### ISSUE TITLE
AppImage not starting

### ISSUE THREAD

**Issue by maddler** [realmazharhussain/gdm-settings#9]
Just wnated to give this a try on Ubuntu 21.10 but getting this:

```
 ./Login_Manager_Settings-nodeps.AppImage
Traceback (most recent call last):
  File "/tmp/.mount_Login_072lDm/usr/bin/gdm-settings", line 2, in <module>
    from gdm_settings import gdm_settings_gui
  File "/tmp/.mount_Login_072lDm/usr/lib/python3.10/site-packages/gdm_settings/gdm_settings_gui.py", line 5, in <module>
    gi.require_version("Adw", '1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Adw not available

```
Just let me know if there's any other info I can provide.
Thanks!

**Comment by realmazharhussain** [comment]
The AppImage is incomplete. It does not include any dependencies. You need to manually install all the dependencies.

**Comment by mihalycsaba** [comment]
I cant figure out which dependencies are needed for ubuntu 21.10

**Comment by maddler** [comment]
Ah, my bad.
Thought the "nodep" in the name meant there was no dependency needed, rather than no dependency included.

WM


________________________________

**Comment by realmazharhussain** [comment]
@mihalycsaba
> I cant figure out which dependencies are needed for ubuntu 21.10

Ubuntu 21.10 does not have LibAdwaita. This app cannot be installed on 21.10 manually. You will have to wait for a proper AppImage, Flatpak or Snap package.

**Comment by realmazharhussain** [comment]
Hi, guys!

After so much time, a "sensible" AppImage has finally been built. It *should* work on Ubuntu 21.10, Fedora 35, etc. and some earlier versions of those distros along with other distros.

Here is the link https://drive.google.com/file/d/1pUFaq0ZuG3b2K4YpzE7vRv8cgc5Odtd9/view?usp=sharing

**Comment by realmazharhussain** [comment]
Version 1.0-beta.4 has been released with a functioning AppImage. You can download the AppImage from [releases](https://github.com/realmazharhussain/gdm-settings/releases) page.

Closing the issue now.
