### ISSUE TITLE
Polish @thalesruan icon

### ISSUE THREAD

**Issue by daudix-UFO** [realmazharhussain/gdm-settings#92]
### Description

Hello, recently this project updated his icon to GNOME HIG one, but I noticed a few incorrect things, and liked to fix them, as well as make a few new variants

# Current (Fixed)

![1](https://user-images.githubusercontent.com/77155297/186023028-34495db4-4a8c-42c9-9db3-5d0446b61568.png)
![2](https://user-images.githubusercontent.com/77155297/186023045-91bc2ace-1c8e-4332-b8f1-5c2b2d864c30.png)
![3](https://user-images.githubusercontent.com/77155297/186023057-9d3e9173-f826-4965-bd98-87e7581b607d.png)
![4](https://user-images.githubusercontent.com/77155297/186023063-80ea9407-26a5-4549-9c0a-2b5ebb3b8806.png)

# New

![1a](https://user-images.githubusercontent.com/77155297/186023235-534a37ad-a21a-4fd6-aab4-b836bbd0368b.png)
![2a](https://user-images.githubusercontent.com/77155297/186023241-8f64a076-746d-4bb8-961a-499484cd916a.png)
![3a](https://user-images.githubusercontent.com/77155297/186023246-6af6b04d-432f-4f2d-9927-2b89f7a86d0a.png)

# Symbolic

![1-s](https://user-images.githubusercontent.com/77155297/186023454-3edb5185-bc3a-474e-bb25-92341ebed278.png)

### Explaination

This is preview of icons, when we will select (or not) the icon, I will make a PR, and if @thalesruan will make it, I will be happy

_There is a Nightly version for all icons, but there already a lot of screenshots :P_

**Comment by thalesruan** [comment]
I get really proud for you asking my approbation, and I REALLY liked the icons you done. My favorite is that:
![image](https://user-images.githubusercontent.com/7895807/186027744-c4fc1c40-1890-4059-8b70-34665ede7300.png)

Thank you for polish my creation, you took it to another level! If you're waiting to know if I approved it, I give you a big YES! haha

**Comment by daudix-UFO** [comment]
I am happy that you liked it, here is all Source files, Screenshots and  Alt versions

[📎 GDM Settings.zip](https://github.com/realmazharhussain/gdm-settings/files/9397953/GDM.Settings.zip)

Icon that you liked and symbolic

[📎 GDM Settings - less.zip](https://github.com/realmazharhussain/gdm-settings/files/9397963/GDM.Settings.-.less.zip)

**Comment by daudix-UFO** [comment]
Will you make a pull request?

**Comment by realmazharhussain** [comment]
> Hello, recently this project updated his icon to GNOME HIG one, but I noticed a few incorrect things, and liked to fix them, as well as make a few new variants

Thank you very much for contribiting. I really appreciate it. But I would like to know what was incorrect in the original icon that you have fixed.

Also, the new icons you created are great. But there is just one small problem; they are blue all over the place. There should be more contrast between user-avatar/input-field and the background color.

**Comment by daudix-UFO** [comment]
About incorrect things, they actually more like fixes, different margins, size of objects, colors and etc

About new icon contrast, the idea of blue is to make it look like lockscreen, there is a version with grey avatar and password prompt, but it look not that good

![image](https://user-images.githubusercontent.com/77155297/186061160-c0376a91-cd9a-4c6c-8f4b-e2e2324c0cab.png)

**Comment by realmazharhussain** [comment]
For a brief period of time, I tried to design a new icon with GNOME HIG myself. I matched its colors with GDM login screen and the colors did look good. The colors were like this

Background: Dark Grey
User Avatar: Blue
Input Field: White

Those are the colors of the default GDM login screen.

**Comment by thalesruan** [comment]
@realmazharhussain I think that the contrast is not necessary in this case, cause we're talking about an icon, and the real GDM screen and its representation as an icon is two different things for different purposes. The contrast between password-input/avatar and the background in GDM is for the users see where they need to type their passwords. But in icon, the contraste between this elements is not important, all the user has to do is to recognize that it represents the GDM screen. In time, I'm sorry for any grammar error, my English is not that good 😅

**Comment by daudix-UFO** [comment]
> For a brief period of time, I tried to design a new icon with GNOME HIG myself. I matched its colors with GDM login screen and the colors did look good. The colors were like this
> 
> Background: Dark Grey User Avatar: Blue Input Field: White (or Black; I'm not too sure about this one)
> 
> Those are the colors of the default GDM login screen.
> 
> This is a WIP version of that for reference
> 
> ![app icon](https://github.com/realmazharhussain/gdm-settings/raw/be7bfcdbf35d264a96ca96710f7b268cec1113d2/data/icons/io.github.realmazharhussain.GdmSettings.Source.svg)

Actually looks good!

**Comment by realmazharhussain** [comment]
> I think that the contrast is not necessary in this case, cause we're talking about an icon, and the real GDM screen and its representation as an icon is two different things for different purposes.

Colors don't have to match the login screen but they need to have some contrast. Contrast enhances an icon's beauty IMO.
