### ISSUE TITLE
"Apply Current Display Settings" failed to apply display settings

### ISSUE THREAD

**Issue by TDuffinNTU** [realmazharhussain/gdm-settings#93]
error message in the terminal when I attempt to apply my settings.

```
install: missing destination file operand after '~{tduff,gdm}/.config/monitors.xml'
Try 'install --help' for more information.
chown: cannot access '/var/lib/gdm3/.config/monitors.xml': No such file or directory

```

I'm on Pop!_OS 22.04 LTS  |  5.19.0-76051900-generic Kernel
WM  |  Mutter
DE   |  GNOME 42.3.1

**Comment by realmazharhussain** [comment]
And application version??

**Comment by TDuffinNTU** [comment]
0.6 I believe? the most recent version over flathub. I'll check once I'm off work :)

**Comment by realmazharhussain** [comment]
I'll have to check it but I think the issue does not exist in the latest source code.

**Comment by realmazharhussain** [comment]
Yes. I checked and the problem does not exist in the latest source code.

Now, you can either wait for v1.0 to release or you could compile and install the beta version from source.

**Comment by realmazharhussain** [comment]
Duplicate of #71.
