### ISSUE TITLE
no Chinese translation can be seen on a chinese language linux

### ISSUE THREAD

**Issue by valig5** [realmazharhussain/gdm-settings#97]
### What happened?

no chinese translation can be seen on a chinese language linux

### Expected behavior

should seen the correct translation

### To Reproduce

change system language to 中文(简体)

### Detailed Explaination (Optional)

linux dont use zh_Hans , try change the character set to zh_CN instead. 

RIGHT
![截图 2022-08-28 20-05-26](https://user-images.githubusercontent.com/85693457/187073459-0f0b5db5-002f-4a41-82b2-0fb524d7e592.png)

WRONG
![截图 2022-08-28 20-07-14](https://user-images.githubusercontent.com/85693457/187073460-f4476f17-9ea4-4bc5-9803-e9025c2d2500.png)

### Application Version

0.6 gdm-settings-git

### Source

AUR

### Environment

- **OS**: Arch Linux
- **GNOME**: 42.4

**Comment by realmazharhussain** [comment]
Try this version.

[gdm-settings-1.0+beta-1-any.pkg.tar.zst.zip](https://github.com/realmazharhussain/gdm-settings/files/9440201/gdm-settings-1.0%2Bbeta-1-any.pkg.tar.zst.zip)

**Note:** It is an ArchLinux package archived in zip format. First unzip it and then install it like you would normally install a local .tar.zst package.
