### ISSUE TITLE
Add bing wallpaper feature | Integrate with gnome bing extension

### ISSUE THREAD

**Issue by FaisalRehman234** [realmazharhussain/gdm-settings#98]
### Description

Add a feature to automatically change gdm background with bing wallpaper changer gnome extension. Integrate with [Bing Wallpepr Changer](https://extensions.gnome.org/extension/1262/bing-wallpaper-changer/)

**Comment by realmazharhussain** [comment]
Sorry, bro.

This app is just a big hack which implements [these smaller hacks](https://wiki.archlinux.org/title/GDM#Configuration) from the [Arch Wiki](https://wiki.archlinux.org) as a GTK app. And there is no way (that I know of) to enable GNOME Shell extensions for GDM.

**Comment by FaisalRehman234** [comment]
But thank you for for developing this application. I appreciate it.
