### ISSUE TITLE
Enable Logo not working for Fedora 36

### ISSUE THREAD

**Issue by BaktashGorgani** [realmazharhussain/gdm-settings#99]
### What happened?

I am having an issue with the "Enable Logo" setting inside of the Miscellaneous tab. I have enabled the setting and put a ".png" image of Fedora's logo but it is not showing up on the login screen.

### Expected behavior

I would expect the logo to be added below the user list

### To Reproduce

Turn on "Enable Logo" and select a file in ~/documents

### Application Version

gdm-settings v0.6

### Source

Flatpak

### Environment

- **OS**: Fedora 36 Workstation 5.19.4-200.fc36.x86_64 (64-bit)
- **Desktop Manager**: GDM
- **GNOME Shell**: 42.4

- **Desktop Environment**:
KDE Plasma Version: 5.25.4
KDE Frameworks Version 5.97.0
Qt Version: 5.15.5
Graphics Platform: X11

**Comment by realmazharhussain** [comment]
Can you provide the output of the following command?

```bash
grep logo /etc/dconf/db/gdm.d/95-gdm-settings
```

**Comment by BaktashGorgani** [comment]
Surely, plese find the output below:

`[baky@baky-fedora-pc ~]$ grep logo /etc/dconf/db/gdm.d/95-gdm-settings
logo='/run/user/1000/doc/94da248a/Fedora_vertical.png'
[baky@baky-fedora-pc ~]$ ls -1 /run/user/$(id -u)/doc/by-app/io.github.realmazharhussain.GdmSettings/*
/run/user/1000/doc/by-app/io.github.realmazharhussain.GdmSettings/51104af5:
162202193660ae1730834946.53737010.jpg

/run/user/1000/doc/by-app/io.github.realmazharhussain.GdmSettings/94da248a:
Fedora_vertical.png

/run/user/1000/doc/by-app/io.github.realmazharhussain.GdmSettings/d215eb19:
ls: cannot access '/run/user/1000/doc/by-app/io.github.realmazharhussain.GdmSettings/d215eb19/162202193660ae1730834946.53737010.jpg': No such file or directory
162202193660ae1730834946.53737010.jpg
`

When I reset the settings and use the default GDM settings the default fedora logo is there.

**Comment by realmazharhussain** [comment]
What is the output of the following command?

```bash
test -f /run/user/1000/doc/94da248a/Fedora_vertical.png; echo $?
```

Also,

After you apply settings, log out instead of rebooting and see if logo is there.

**Comment by realmazharhussain** [comment]
Forget everything I said above. The reason for this issue seems to be how the file chooser portal works. I'm trying to resolve the issue. In the meantime, you could download the [AppImage](https://github.com/realmazharhussain/gdm-settings/releases/latest/download/Login_Manager_Settings-nodeps.AppImage) or install the app from source. Those versions seem to work.

**Comment by BaktashGorgani** [comment]
Not a big issue. I will wait for your official release. Thanks!
